import psycopg


def create_access_schema(connection: psycopg.Connection) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS tcp_user (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT NOT NULL UNIQUE,
            full_name TEXT NOT NULL,
            password_hash TEXT NOT NULL,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            current_level TEXT,
            target_level TEXT,
            CONSTRAINT current_level_check CHECK (
                current_level IS NULL OR current_level IN ('P4','P5','P6','P7','P8')
            ),
            CONSTRAINT target_level_check CHECK (
                target_level IS NULL OR target_level IN ('P4','P5','P6','P7','P8')
            )
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS tcp_role (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS tcp_user_role (
            user_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE,
            role_id BIGINT NOT NULL REFERENCES tcp_role(id) ON DELETE CASCADE,
            PRIMARY KEY (user_id, role_id)
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS tcp_session (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            token_hash TEXT NOT NULL UNIQUE,
            user_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE,
            expires_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS buddy_relationship (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            member_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE,
            buddy_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE,
            effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
            effective_to DATE,
            is_primary BOOLEAN NOT NULL DEFAULT TRUE,
            effective_date DATE,
            expiry_date DATE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            CHECK (member_id <> buddy_id),
            CHECK (effective_date IS NULL OR expiry_date IS NULL
                   OR effective_date <= expiry_date)
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS tcp_system_config (
            code TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            value TEXT NOT NULL,
            value_type TEXT NOT NULL DEFAULT 'text',
            description TEXT NOT NULL DEFAULT '',
            enabled BOOLEAN NOT NULL DEFAULT TRUE,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_session_token_hash
        ON tcp_session(token_hash)
        """
    )
    connection.execute(
        """
        INSERT INTO tcp_system_config (code, name, value, value_type, description)
        VALUES
            ('assessment_window', '年度评估窗口', '全年', 'text', '年度评估开放时间'),
            ('homepage_todo_rule', '首页待办展示规则', '全部待办', 'text',
             '首页待办筛选规则'),
            ('default_plan_cycle', '默认计划周期', '12', 'integer',
             '年度成长计划默认月数')
        ON CONFLICT (code) DO NOTHING
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_session_expires
        ON tcp_session(expires_at)
        """
    )
    # Migration: add current_level / target_level to existing tcp_user tables
    for col, constraint in [
        (
            "current_level",
            "current_level IS NULL OR current_level IN ('P4','P5','P6','P7','P8')",
        ),
        (
            "target_level",
            "target_level IS NULL OR target_level IN ('P4','P5','P6','P7','P8')",
        ),
    ]:
        connection.execute(f"ALTER TABLE tcp_user ADD COLUMN IF NOT EXISTS {col} TEXT")
        # Drop old constraint without level list then re-add
        connection.execute(
            f"ALTER TABLE tcp_user DROP CONSTRAINT IF EXISTS {col}_check"
        )
        connection.execute(
            f"ALTER TABLE tcp_user ADD CONSTRAINT {col}_check CHECK ({constraint})"
        )
    connection.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS unique_active_primary_buddy
        ON buddy_relationship(member_id)
        WHERE is_primary = TRUE AND effective_to IS NULL
        """
    )
    # Migration: add effective_date/expiry_date/created_at/updated_at to existing tables
    for col, col_type, col_default in [
        ("effective_date", "DATE", None),
        ("expiry_date", "DATE", None),
        ("created_at", "TIMESTAMPTZ", "NOW()"),
        ("updated_at", "TIMESTAMPTZ", "NOW()"),
    ]:
        if col_default:
            connection.execute(
                f"ALTER TABLE buddy_relationship ADD COLUMN IF NOT EXISTS "
                f"{col} {col_type} NOT NULL DEFAULT {col_default}"
            )
        else:
            connection.execute(
                f"ALTER TABLE buddy_relationship ADD COLUMN IF NOT EXISTS "
                f"{col} {col_type}"
            )
    # Backfill effective_date/expiry_date from effective_from/effective_to
    connection.execute(
        """UPDATE buddy_relationship
           SET effective_date = effective_from
           WHERE effective_date IS NULL"""
    )
    connection.execute(
        """UPDATE buddy_relationship
           SET expiry_date = effective_to
           WHERE expiry_date IS NULL AND effective_to IS NOT NULL"""
    )
    # Add date order constraint
    connection.execute(
        """ALTER TABLE buddy_relationship
           DROP CONSTRAINT IF EXISTS buddy_relationship_date_check"""
    )
    connection.execute(
        """ALTER TABLE buddy_relationship
           ADD CONSTRAINT buddy_relationship_date_check
           CHECK (effective_date IS NULL OR expiry_date IS NULL
                  OR effective_date <= expiry_date)"""
    )
    # Drop legacy unique index, add new one based on effective_date/expiry_date
    connection.execute("""DROP INDEX IF EXISTS unique_active_primary_buddy""")
    connection.execute(
        """CREATE UNIQUE INDEX IF NOT EXISTS unique_active_primary_buddy
           ON buddy_relationship(member_id)
           WHERE is_primary = TRUE AND expiry_date IS NULL"""
    )
    connection.execute(
        """
        INSERT INTO tcp_role (code, name)
        VALUES
            ('Member', 'Member'),
            ('Buddy', 'Buddy'),
            ('Leader', 'Leader'),
            ('Admin', 'Admin')
        ON CONFLICT (code) DO NOTHING
        """
    )
