--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: set_annual_growth_plan_default_dates(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.set_annual_growth_plan_default_dates() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        BEGIN
            IF NEW.start_date IS NULL THEN
                NEW.start_date := MAKE_DATE(NEW.year, 1, 1);
            END IF;
            IF NEW.end_date IS NULL THEN
                NEW.end_date := MAKE_DATE(NEW.year, 12, 31);
            END IF;
            RETURN NEW;
        END;
        $$;


--
-- Name: validate_capability_node_hierarchy(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.validate_capability_node_hierarchy() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        DECLARE
            parent_type TEXT;
            parent_model_id BIGINT;
        BEGIN
            IF NEW.node_type = 'L1' THEN
                IF NEW.parent_node_id IS NOT NULL THEN
                    RAISE EXCEPTION 'L1 capability nodes cannot have a parent';
                END IF;
            ELSE
                SELECT node_type, model_id
                INTO parent_type, parent_model_id
                FROM capability_node
                WHERE id = NEW.parent_node_id;

                IF NOT FOUND
                   OR parent_model_id <> NEW.model_id
                   OR (NEW.node_type = 'L2' AND parent_type <> 'L1')
                   OR (NEW.node_type = 'L3' AND parent_type <> 'L2') THEN
                    RAISE EXCEPTION 'invalid capability node parent hierarchy';
                END IF;
            END IF;

            IF EXISTS (
                SELECT 1
                FROM capability_node AS child
                WHERE child.parent_node_id = NEW.id
                  AND (
                      child.model_id <> NEW.model_id
                      OR (child.node_type = 'L2' AND NEW.node_type <> 'L1')
                      OR (child.node_type = 'L3' AND NEW.node_type <> 'L2')
                  )
            ) THEN
                RAISE EXCEPTION 'capability node update would invalidate a child';
            END IF;

            IF NEW.node_type <> 'L3' AND EXISTS (
                SELECT 1
                FROM capability_node_resource
                WHERE node_id = NEW.id
            ) THEN
                RAISE EXCEPTION 'only L3 capability nodes can link resources';
            END IF;

            RETURN NEW;
        END;
        $$;


--
-- Name: validate_capability_node_resource(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.validate_capability_node_resource() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        BEGIN
            IF (
                SELECT node_type FROM capability_node WHERE id = NEW.node_id
            ) <> 'L3' THEN
                RAISE EXCEPTION 'only L3 capability nodes can link resources';
            END IF;
            RETURN NEW;
        END;
        $$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: annual_growth_plan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.annual_growth_plan (
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    year integer NOT NULL,
    plan_cycle integer DEFAULT 12 NOT NULL,
    status text DEFAULT '制定中'::text NOT NULL,
    start_date date,
    end_date date,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT annual_growth_plan_status_check CHECK ((status = ANY (ARRAY['制定中'::text, '执行中'::text, '已归档'::text])))
);


--
-- Name: annual_growth_plan_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.annual_growth_plan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.annual_growth_plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assessment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assessment (
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    year integer NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    assessment_type text NOT NULL,
    status text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    submitted_at timestamp with time zone,
    archived_at timestamp with time zone,
    revision bigint DEFAULT 1 NOT NULL,
    CONSTRAINT assessment_assessment_type_check CHECK ((assessment_type = ANY (ARRAY['年度'::text, '年中更新'::text, '晋升复核'::text]))),
    CONSTRAINT assessment_status_check CHECK ((status = ANY (ARRAY['草稿'::text, '待复核'::text, '已复核'::text, '建议调整'::text, '已归档'::text])))
);


--
-- Name: assessment_detail; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assessment_detail (
    id bigint NOT NULL,
    assessment_id bigint NOT NULL,
    l3_code text NOT NULL,
    current_level integer,
    current_level_explicitly_cleared boolean DEFAULT false NOT NULL,
    target_level integer,
    standard_target_applicable boolean,
    standard_target_level integer,
    target_adjusted boolean DEFAULT false NOT NULL,
    adjusted_target_level integer,
    target_adjustment_reason text,
    target_snapshot_source text,
    target_compatibility_error text,
    gap_value integer,
    evidence_note text,
    plan_candidate boolean DEFAULT false NOT NULL,
    inherited_from_assessment_id bigint,
    inherited_current_level integer,
    inherited_evidence_note text,
    CONSTRAINT assessment_detail_adjusted_target_level_check CHECK (((adjusted_target_level IS NULL) OR ((adjusted_target_level >= 1) AND (adjusted_target_level <= 5)))),
    CONSTRAINT assessment_detail_check CHECK (((standard_target_applicable IS DISTINCT FROM false) OR (standard_target_level IS NULL))),
    CONSTRAINT assessment_detail_check1 CHECK ((((target_adjusted = false) AND (adjusted_target_level IS NULL) AND (target_adjustment_reason IS NULL)) OR ((target_adjusted = true) AND (standard_target_applicable = true) AND ((adjusted_target_level >= 1) AND (adjusted_target_level <= 5)) AND (btrim(target_adjustment_reason) <> ''::text)))),
    CONSTRAINT assessment_detail_current_level_check CHECK (((current_level IS NULL) OR ((current_level >= 1) AND (current_level <= 5)))),
    CONSTRAINT assessment_detail_inherited_current_level_check CHECK (((inherited_current_level IS NULL) OR ((inherited_current_level >= 1) AND (inherited_current_level <= 5)))),
    CONSTRAINT assessment_detail_not_applicable_check CHECK (((standard_target_applicable IS DISTINCT FROM false) OR (standard_target_level IS NULL))),
    CONSTRAINT assessment_detail_standard_target_level_check CHECK (((standard_target_level IS NULL) OR ((standard_target_level >= 1) AND (standard_target_level <= 5)))),
    CONSTRAINT assessment_detail_target_adjustment_check CHECK ((((target_adjusted = false) AND (adjusted_target_level IS NULL) AND (target_adjustment_reason IS NULL)) OR ((target_adjusted = true) AND (standard_target_applicable = true) AND ((adjusted_target_level >= 1) AND (adjusted_target_level <= 5)) AND (btrim(target_adjustment_reason) <> ''::text)))),
    CONSTRAINT assessment_detail_target_level_check CHECK (((target_level IS NULL) OR ((target_level >= 1) AND (target_level <= 5))))
);


--
-- Name: assessment_detail_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.assessment_detail ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assessment_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assessment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.assessment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assessment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assessment_review; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assessment_review (
    id bigint NOT NULL,
    assessment_id bigint NOT NULL,
    sequence integer NOT NULL,
    buddy_id bigint,
    conclusion text,
    feedback text,
    reviewed_at timestamp with time zone,
    status text NOT NULL,
    CONSTRAINT assessment_review_conclusion_check CHECK ((conclusion = ANY (ARRAY['认可'::text, '建议调整'::text]))),
    CONSTRAINT assessment_review_status_check CHECK ((status = ANY (ARRAY['待复核'::text, '已闭环'::text])))
);


--
-- Name: assessment_review_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.assessment_review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assessment_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: buddy_relationship; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.buddy_relationship (
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    buddy_id bigint NOT NULL,
    effective_from date DEFAULT CURRENT_DATE NOT NULL,
    effective_to date,
    is_primary boolean DEFAULT true NOT NULL,
    effective_date date DEFAULT CURRENT_DATE NOT NULL,
    expiry_date date,
    CONSTRAINT buddy_relationship_check CHECK ((member_id <> buddy_id))
);


--
-- Name: buddy_relationship_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.buddy_relationship ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.buddy_relationship_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: capability_model; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.capability_model (
    id bigint NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    version text NOT NULL,
    source_workbook text NOT NULL,
    source_sheet text NOT NULL,
    source_row integer NOT NULL
);


--
-- Name: capability_model_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.capability_model ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.capability_model_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: capability_node; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.capability_node (
    id bigint NOT NULL,
    model_id bigint NOT NULL,
    parent_node_id bigint,
    node_type text NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    sort_order integer NOT NULL,
    l1_category text,
    overview text,
    enabled boolean DEFAULT true NOT NULL,
    p4_description text,
    p5_description text,
    p6_description text,
    p7_description text,
    p8_description text,
    recommended_start_level text,
    materials_text text,
    expected_output text,
    estimated_hours text,
    output_type text,
    notes text,
    source_workbook text NOT NULL,
    source_sheet text NOT NULL,
    source_row integer NOT NULL,
    CONSTRAINT capability_node_check CHECK ((((node_type = 'L1'::text) AND (parent_node_id IS NULL)) OR ((node_type = ANY (ARRAY['L2'::text, 'L3'::text])) AND (parent_node_id IS NOT NULL)))),
    CONSTRAINT capability_node_node_type_check CHECK ((node_type = ANY (ARRAY['L1'::text, 'L2'::text, 'L3'::text])))
);


--
-- Name: capability_node_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.capability_node ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.capability_node_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: capability_node_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.capability_node_resource (
    node_id bigint NOT NULL,
    resource_id bigint NOT NULL
);


--
-- Name: capability_profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.capability_profile (
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    year integer NOT NULL,
    status text DEFAULT '已生成'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT capability_profile_status_check CHECK ((status = ANY (ARRAY['生成中'::text, '已生成'::text])))
);


--
-- Name: capability_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.capability_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.capability_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: capability_standard_target_override; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.capability_standard_target_override (
    node_id bigint NOT NULL,
    job_level text NOT NULL,
    target_level integer,
    CONSTRAINT capability_standard_target_override_job_level_check CHECK ((job_level = ANY (ARRAY['P4'::text, 'P5'::text, 'P6'::text, 'P7'::text, 'P8'::text]))),
    CONSTRAINT capability_standard_target_override_target_level_check CHECK (((target_level IS NULL) OR ((target_level >= 1) AND (target_level <= 5))))
);


--
-- Name: evidence; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evidence (
    id bigint NOT NULL,
    learning_task_id bigint NOT NULL,
    l3_code text NOT NULL,
    version_number integer NOT NULL,
    content text,
    evidence_link text,
    status text DEFAULT '草稿'::text NOT NULL,
    submitted_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT evidence_status_check CHECK ((status = ANY (ARRAY['草稿'::text, '待 Review'::text, '通过'::text, '需补充'::text, '驳回'::text, '已归档'::text]))),
    CONSTRAINT evidence_version_number_check CHECK ((version_number > 0))
);


--
-- Name: evidence_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.evidence ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evidence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evidence_review; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evidence_review (
    id bigint NOT NULL,
    evidence_id bigint NOT NULL,
    buddy_id bigint NOT NULL,
    status text DEFAULT '待 Review'::text NOT NULL,
    conclusion text,
    feedback text,
    reviewed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT evidence_review_conclusion_check CHECK ((conclusion = ANY (ARRAY['通过'::text, '需补充'::text, '驳回'::text]))),
    CONSTRAINT evidence_review_status_check CHECK ((status = ANY (ARRAY['待 Review'::text, '通过'::text, '需补充'::text, '驳回'::text, '已闭环'::text])))
);


--
-- Name: evidence_review_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.evidence_review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evidence_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gap; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.gap (
    id bigint NOT NULL,
    assessment_id bigint NOT NULL,
    l3_code text NOT NULL,
    current_level integer NOT NULL,
    target_level integer NOT NULL,
    gap_value integer NOT NULL,
    priority text DEFAULT '中'::text NOT NULL,
    plan_candidate boolean DEFAULT false NOT NULL,
    CONSTRAINT gap_priority_check CHECK ((priority = ANY (ARRAY['高'::text, '中'::text, '低'::text])))
);


--
-- Name: gap_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.gap ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gap_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: growth_goal; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.growth_goal (
    id bigint NOT NULL,
    gap_id bigint NOT NULL,
    annual_growth_plan_id bigint NOT NULL,
    l3_code text NOT NULL,
    year integer NOT NULL,
    target_level integer NOT NULL,
    priority text DEFAULT '中'::text NOT NULL,
    CONSTRAINT growth_goal_priority_check CHECK ((priority = ANY (ARRAY['高'::text, '中'::text, '低'::text])))
);


--
-- Name: growth_goal_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.growth_goal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.growth_goal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: learning_progress_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.learning_progress_log (
    id bigint NOT NULL,
    task_id bigint NOT NULL,
    record_date date NOT NULL,
    actual_hours integer NOT NULL,
    note text,
    recorder_id bigint NOT NULL,
    CONSTRAINT learning_progress_log_actual_hours_check CHECK ((actual_hours >= 0))
);


--
-- Name: learning_progress_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.learning_progress_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.learning_progress_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: learning_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.learning_resource (
    id bigint NOT NULL,
    material_code text NOT NULL,
    name text NOT NULL,
    material_type text NOT NULL,
    source_text text NOT NULL,
    purpose text NOT NULL,
    status text NOT NULL,
    source_workbook text NOT NULL,
    source_sheet text NOT NULL,
    source_row integer NOT NULL
);


--
-- Name: learning_resource_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.learning_resource ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.learning_resource_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: learning_task; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.learning_task (
    id bigint NOT NULL,
    plan_item_id bigint NOT NULL,
    l3_code text NOT NULL,
    status text DEFAULT '未开始'::text NOT NULL,
    actual_start_date date,
    actual_end_date date,
    actual_hours integer DEFAULT 0,
    completion_quality text,
    review_conclusion text,
    next_action text,
    CONSTRAINT learning_task_status_check CHECK ((status = ANY (ARRAY['未开始'::text, '进行中'::text, '待 Evidence Review'::text, '已完成'::text, '延期'::text, '暂停'::text, '取消'::text])))
);


--
-- Name: learning_task_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.learning_task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.learning_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plan_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plan_item (
    id bigint NOT NULL,
    annual_growth_plan_id bigint NOT NULL,
    growth_goal_id bigint NOT NULL,
    l3_code text NOT NULL,
    current_level integer NOT NULL,
    target_level integer NOT NULL,
    priority text DEFAULT '中'::text NOT NULL,
    learning_material text,
    learning_task_content text,
    expected_output text,
    estimated_hours text,
    plan_start_date date,
    plan_end_date date,
    target_month integer,
    status text DEFAULT '未开始'::text NOT NULL,
    CONSTRAINT plan_item_priority_check CHECK ((priority = ANY (ARRAY['高'::text, '中'::text, '低'::text]))),
    CONSTRAINT plan_item_status_check CHECK ((status = ANY (ARRAY['未开始'::text, '进行中'::text, '已完成'::text, '延期'::text, '暂停'::text, '取消'::text])))
);


--
-- Name: plan_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plan_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plan_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migration; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migration (
    version text NOT NULL,
    applied_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: tcp_role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tcp_role (
    id bigint NOT NULL,
    code text NOT NULL,
    name text NOT NULL
);


--
-- Name: tcp_role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tcp_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tcp_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tcp_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tcp_session (
    id bigint NOT NULL,
    token_hash text NOT NULL,
    user_id bigint NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: tcp_session_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tcp_session ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tcp_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tcp_system_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tcp_system_config (
    code text NOT NULL,
    name text NOT NULL,
    value text NOT NULL,
    value_type text DEFAULT 'text'::text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: tcp_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tcp_user (
    id bigint NOT NULL,
    username text NOT NULL,
    full_name text NOT NULL,
    password_hash text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    current_level text,
    target_level text,
    CONSTRAINT current_level_check CHECK (((current_level IS NULL) OR (current_level = ANY (ARRAY['P4'::text, 'P5'::text, 'P6'::text, 'P7'::text, 'P8'::text])))),
    CONSTRAINT target_level_check CHECK (((target_level IS NULL) OR (target_level = ANY (ARRAY['P4'::text, 'P5'::text, 'P6'::text, 'P7'::text, 'P8'::text]))))
);


--
-- Name: tcp_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tcp_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tcp_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tcp_user_role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tcp_user_role (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


--
-- Name: team_annual_capability_plan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.team_annual_capability_plan (
    id bigint NOT NULL,
    code text NOT NULL,
    year integer NOT NULL,
    publisher_id bigint NOT NULL,
    resource_arrangement text,
    description text,
    published_at timestamp with time zone DEFAULT now() NOT NULL,
    status text DEFAULT '已发布'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT team_annual_capability_plan_status_check CHECK ((status = ANY (ARRAY['已发布'::text, '已归档'::text])))
);


--
-- Name: team_annual_capability_plan_domain; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.team_annual_capability_plan_domain (
    plan_id bigint NOT NULL,
    l1_code text NOT NULL
);


--
-- Name: team_annual_capability_plan_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.team_annual_capability_plan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_annual_capability_plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: annual_growth_plan annual_growth_plan_member_id_year_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annual_growth_plan
    ADD CONSTRAINT annual_growth_plan_member_id_year_key UNIQUE (member_id, year);


--
-- Name: annual_growth_plan annual_growth_plan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annual_growth_plan
    ADD CONSTRAINT annual_growth_plan_pkey PRIMARY KEY (id);


--
-- Name: assessment_detail assessment_detail_assessment_id_l3_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_detail
    ADD CONSTRAINT assessment_detail_assessment_id_l3_code_key UNIQUE (assessment_id, l3_code);


--
-- Name: assessment_detail assessment_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_detail
    ADD CONSTRAINT assessment_detail_pkey PRIMARY KEY (id);


--
-- Name: assessment assessment_member_id_year_version_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment
    ADD CONSTRAINT assessment_member_id_year_version_key UNIQUE (member_id, year, version);


--
-- Name: assessment assessment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment
    ADD CONSTRAINT assessment_pkey PRIMARY KEY (id);


--
-- Name: assessment_review assessment_review_assessment_id_sequence_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_review
    ADD CONSTRAINT assessment_review_assessment_id_sequence_key UNIQUE (assessment_id, sequence);


--
-- Name: assessment_review assessment_review_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_review
    ADD CONSTRAINT assessment_review_pkey PRIMARY KEY (id);


--
-- Name: buddy_relationship buddy_relationship_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.buddy_relationship
    ADD CONSTRAINT buddy_relationship_pkey PRIMARY KEY (id);


--
-- Name: capability_model capability_model_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.capability_model
    ADD CONSTRAINT capability_model_code_key UNIQUE (code);


--
-- Name: capability_model capability_model_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.capability_model
    ADD CONSTRAINT capability_model_pkey PRIMARY KEY (id);


--
-- Name: capability_node capability_node_model_id_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.capability_node
    ADD CONSTRAINT capability_node_model_id_code_key UNIQUE (model_id, code);


--
-- Name: capability_node capability_node_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.capability_node
    ADD CONSTRAINT capability_node_pkey PRIMARY KEY (id);


--
-- Name: capability_node_resource capability_node_resource_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.capability_node_resource
    ADD CONSTRAINT capability_node_resource_pkey PRIMARY KEY (node_id, resource_id);


--
-- Name: capability_profile capability_profile_member_id_year_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.capability_profile
    ADD CONSTRAINT capability_profile_member_id_year_key UNIQUE (member_id, year);


--
-- Name: capability_profile capability_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.capability_profile
    ADD CONSTRAINT capability_profile_pkey PRIMARY KEY (id);


--
-- Name: capability_standard_target_override capability_standard_target_override_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.capability_standard_target_override
    ADD CONSTRAINT capability_standard_target_override_pkey PRIMARY KEY (node_id, job_level);


--
-- Name: evidence evidence_learning_task_id_version_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence
    ADD CONSTRAINT evidence_learning_task_id_version_number_key UNIQUE (learning_task_id, version_number);


--
-- Name: evidence evidence_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence
    ADD CONSTRAINT evidence_pkey PRIMARY KEY (id);


--
-- Name: evidence_review evidence_review_evidence_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence_review
    ADD CONSTRAINT evidence_review_evidence_id_key UNIQUE (evidence_id);


--
-- Name: evidence_review evidence_review_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence_review
    ADD CONSTRAINT evidence_review_pkey PRIMARY KEY (id);


--
-- Name: gap gap_assessment_id_l3_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gap
    ADD CONSTRAINT gap_assessment_id_l3_code_key UNIQUE (assessment_id, l3_code);


--
-- Name: gap gap_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gap
    ADD CONSTRAINT gap_pkey PRIMARY KEY (id);


--
-- Name: growth_goal growth_goal_annual_growth_plan_id_l3_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.growth_goal
    ADD CONSTRAINT growth_goal_annual_growth_plan_id_l3_code_key UNIQUE (annual_growth_plan_id, l3_code);


--
-- Name: growth_goal growth_goal_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.growth_goal
    ADD CONSTRAINT growth_goal_pkey PRIMARY KEY (id);


--
-- Name: learning_progress_log learning_progress_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_progress_log
    ADD CONSTRAINT learning_progress_log_pkey PRIMARY KEY (id);


--
-- Name: learning_resource learning_resource_material_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_resource
    ADD CONSTRAINT learning_resource_material_code_key UNIQUE (material_code);


--
-- Name: learning_resource learning_resource_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_resource
    ADD CONSTRAINT learning_resource_pkey PRIMARY KEY (id);


--
-- Name: learning_task learning_task_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_task
    ADD CONSTRAINT learning_task_pkey PRIMARY KEY (id);


--
-- Name: learning_task learning_task_plan_item_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_task
    ADD CONSTRAINT learning_task_plan_item_id_key UNIQUE (plan_item_id);


--
-- Name: plan_item plan_item_annual_growth_plan_id_l3_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_item
    ADD CONSTRAINT plan_item_annual_growth_plan_id_l3_code_key UNIQUE (annual_growth_plan_id, l3_code);


--
-- Name: plan_item plan_item_growth_goal_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_item
    ADD CONSTRAINT plan_item_growth_goal_id_key UNIQUE (growth_goal_id);


--
-- Name: plan_item plan_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_item
    ADD CONSTRAINT plan_item_pkey PRIMARY KEY (id);


--
-- Name: schema_migration schema_migration_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migration
    ADD CONSTRAINT schema_migration_pkey PRIMARY KEY (version);


--
-- Name: tcp_role tcp_role_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tcp_role
    ADD CONSTRAINT tcp_role_code_key UNIQUE (code);


--
-- Name: tcp_role tcp_role_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tcp_role
    ADD CONSTRAINT tcp_role_pkey PRIMARY KEY (id);


--
-- Name: tcp_session tcp_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tcp_session
    ADD CONSTRAINT tcp_session_pkey PRIMARY KEY (id);


--
-- Name: tcp_session tcp_session_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tcp_session
    ADD CONSTRAINT tcp_session_token_hash_key UNIQUE (token_hash);


--
-- Name: tcp_system_config tcp_system_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tcp_system_config
    ADD CONSTRAINT tcp_system_config_pkey PRIMARY KEY (code);


--
-- Name: tcp_user tcp_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tcp_user
    ADD CONSTRAINT tcp_user_pkey PRIMARY KEY (id);


--
-- Name: tcp_user_role tcp_user_role_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tcp_user_role
    ADD CONSTRAINT tcp_user_role_pkey PRIMARY KEY (user_id, role_id);


--
-- Name: tcp_user tcp_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tcp_user
    ADD CONSTRAINT tcp_user_username_key UNIQUE (username);


--
-- Name: team_annual_capability_plan team_annual_capability_plan_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_annual_capability_plan
    ADD CONSTRAINT team_annual_capability_plan_code_key UNIQUE (code);


--
-- Name: team_annual_capability_plan_domain team_annual_capability_plan_domain_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_annual_capability_plan_domain
    ADD CONSTRAINT team_annual_capability_plan_domain_pkey PRIMARY KEY (plan_id, l1_code);


--
-- Name: team_annual_capability_plan team_annual_capability_plan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_annual_capability_plan
    ADD CONSTRAINT team_annual_capability_plan_pkey PRIMARY KEY (id);


--
-- Name: team_annual_capability_plan team_annual_capability_plan_year_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_annual_capability_plan
    ADD CONSTRAINT team_annual_capability_plan_year_key UNIQUE (year);


--
-- Name: idx_evidence_learning_task_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_evidence_learning_task_id ON public.evidence USING btree (learning_task_id);


--
-- Name: idx_evidence_review_buddy_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_evidence_review_buddy_id ON public.evidence_review USING btree (buddy_id);


--
-- Name: idx_evidence_review_evidence_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_evidence_review_evidence_id ON public.evidence_review USING btree (evidence_id);


--
-- Name: idx_learning_progress_log_recorder_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_learning_progress_log_recorder_id ON public.learning_progress_log USING btree (recorder_id);


--
-- Name: idx_learning_progress_log_task_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_learning_progress_log_task_id ON public.learning_progress_log USING btree (task_id);


--
-- Name: idx_session_expires; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_session_expires ON public.tcp_session USING btree (expires_at);


--
-- Name: idx_session_token_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_session_token_hash ON public.tcp_session USING btree (token_hash);


--
-- Name: unique_active_primary_buddy; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX unique_active_primary_buddy ON public.buddy_relationship USING btree (member_id) WHERE ((is_primary = true) AND (effective_to IS NULL));


--
-- Name: capability_node capability_node_hierarchy_trigger; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER capability_node_hierarchy_trigger BEFORE INSERT OR UPDATE OF node_type, parent_node_id, model_id ON public.capability_node FOR EACH ROW EXECUTE FUNCTION public.validate_capability_node_hierarchy();


--
-- Name: capability_node_resource capability_node_resource_type_trigger; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER capability_node_resource_type_trigger BEFORE INSERT OR UPDATE OF node_id ON public.capability_node_resource FOR EACH ROW EXECUTE FUNCTION public.validate_capability_node_resource();


--
-- Name: annual_growth_plan trg_annual_growth_plan_default_dates; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_annual_growth_plan_default_dates BEFORE INSERT ON public.annual_growth_plan FOR EACH ROW EXECUTE FUNCTION public.set_annual_growth_plan_default_dates();


--
-- Name: annual_growth_plan annual_growth_plan_member_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annual_growth_plan
    ADD CONSTRAINT annual_growth_plan_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.tcp_user(id) ON DELETE CASCADE;


--
-- Name: assessment_detail assessment_detail_assessment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_detail
    ADD CONSTRAINT assessment_detail_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessment(id) ON DELETE CASCADE;


--
-- Name: assessment_detail assessment_detail_inherited_from_assessment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_detail
    ADD CONSTRAINT assessment_detail_inherited_from_assessment_id_fkey FOREIGN KEY (inherited_from_assessment_id) REFERENCES public.assessment(id) ON DELETE SET NULL;


--
-- Name: assessment assessment_member_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment
    ADD CONSTRAINT assessment_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.tcp_user(id) ON DELETE CASCADE;


--
-- Name: assessment_review assessment_review_assessment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_review
    ADD CONSTRAINT assessment_review_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessment(id) ON DELETE CASCADE;


--
-- Name: assessment_review assessment_review_buddy_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_review
    ADD CONSTRAINT assessment_review_buddy_id_fkey FOREIGN KEY (buddy_id) REFERENCES public.tcp_user(id) ON DELETE SET NULL;


--
-- Name: buddy_relationship buddy_relationship_buddy_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.buddy_relationship
    ADD CONSTRAINT buddy_relationship_buddy_id_fkey FOREIGN KEY (buddy_id) REFERENCES public.tcp_user(id) ON DELETE CASCADE;


--
-- Name: buddy_relationship buddy_relationship_member_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.buddy_relationship
    ADD CONSTRAINT buddy_relationship_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.tcp_user(id) ON DELETE CASCADE;


--
-- Name: capability_node capability_node_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.capability_node
    ADD CONSTRAINT capability_node_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.capability_model(id) ON DELETE CASCADE;


--
-- Name: capability_node capability_node_parent_node_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.capability_node
    ADD CONSTRAINT capability_node_parent_node_id_fkey FOREIGN KEY (parent_node_id) REFERENCES public.capability_node(id) ON DELETE CASCADE;


--
-- Name: capability_node_resource capability_node_resource_node_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.capability_node_resource
    ADD CONSTRAINT capability_node_resource_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.capability_node(id) ON DELETE CASCADE;


--
-- Name: capability_node_resource capability_node_resource_resource_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.capability_node_resource
    ADD CONSTRAINT capability_node_resource_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES public.learning_resource(id) ON DELETE CASCADE;


--
-- Name: capability_profile capability_profile_member_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.capability_profile
    ADD CONSTRAINT capability_profile_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.tcp_user(id) ON DELETE CASCADE;


--
-- Name: capability_standard_target_override capability_standard_target_override_node_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.capability_standard_target_override
    ADD CONSTRAINT capability_standard_target_override_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.capability_node(id) ON DELETE CASCADE;


--
-- Name: evidence evidence_learning_task_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence
    ADD CONSTRAINT evidence_learning_task_id_fkey FOREIGN KEY (learning_task_id) REFERENCES public.learning_task(id) ON DELETE CASCADE;


--
-- Name: evidence_review evidence_review_buddy_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence_review
    ADD CONSTRAINT evidence_review_buddy_id_fkey FOREIGN KEY (buddy_id) REFERENCES public.tcp_user(id) ON DELETE CASCADE;


--
-- Name: evidence_review evidence_review_evidence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence_review
    ADD CONSTRAINT evidence_review_evidence_id_fkey FOREIGN KEY (evidence_id) REFERENCES public.evidence(id) ON DELETE CASCADE;


--
-- Name: gap gap_assessment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gap
    ADD CONSTRAINT gap_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessment(id) ON DELETE CASCADE;


--
-- Name: growth_goal growth_goal_annual_growth_plan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.growth_goal
    ADD CONSTRAINT growth_goal_annual_growth_plan_id_fkey FOREIGN KEY (annual_growth_plan_id) REFERENCES public.annual_growth_plan(id) ON DELETE CASCADE;


--
-- Name: growth_goal growth_goal_gap_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.growth_goal
    ADD CONSTRAINT growth_goal_gap_id_fkey FOREIGN KEY (gap_id) REFERENCES public.gap(id) ON DELETE CASCADE;


--
-- Name: learning_progress_log learning_progress_log_recorder_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_progress_log
    ADD CONSTRAINT learning_progress_log_recorder_id_fkey FOREIGN KEY (recorder_id) REFERENCES public.tcp_user(id) ON DELETE CASCADE;


--
-- Name: learning_progress_log learning_progress_log_task_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_progress_log
    ADD CONSTRAINT learning_progress_log_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.learning_task(id) ON DELETE CASCADE;


--
-- Name: learning_task learning_task_plan_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_task
    ADD CONSTRAINT learning_task_plan_item_id_fkey FOREIGN KEY (plan_item_id) REFERENCES public.plan_item(id) ON DELETE CASCADE;


--
-- Name: plan_item plan_item_annual_growth_plan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_item
    ADD CONSTRAINT plan_item_annual_growth_plan_id_fkey FOREIGN KEY (annual_growth_plan_id) REFERENCES public.annual_growth_plan(id) ON DELETE CASCADE;


--
-- Name: plan_item plan_item_growth_goal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_item
    ADD CONSTRAINT plan_item_growth_goal_id_fkey FOREIGN KEY (growth_goal_id) REFERENCES public.growth_goal(id) ON DELETE CASCADE;


--
-- Name: tcp_session tcp_session_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tcp_session
    ADD CONSTRAINT tcp_session_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.tcp_user(id) ON DELETE CASCADE;


--
-- Name: tcp_user_role tcp_user_role_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tcp_user_role
    ADD CONSTRAINT tcp_user_role_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.tcp_role(id) ON DELETE CASCADE;


--
-- Name: tcp_user_role tcp_user_role_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tcp_user_role
    ADD CONSTRAINT tcp_user_role_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.tcp_user(id) ON DELETE CASCADE;


--
-- Name: team_annual_capability_plan_domain team_annual_capability_plan_domain_plan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_annual_capability_plan_domain
    ADD CONSTRAINT team_annual_capability_plan_domain_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.team_annual_capability_plan(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--



