"""Issue #61 §7: real pre-v0007 upgrade integration test.

Builds a genuine v0006-era database (master-branch DDL + v0001–v0006 applied
and recorded), seeds legacy business data, then runs the production
run_migrations (v0007/v0008) and the full application lifespan.

Verifies:
- schema_migration order and run-once semantics;
- v0007/v0008 applied exactly once each;
- legacy assessment_detail rows stay readable with values intact;
- member_priority/include_in_plan stay NULL — no fabricated member decisions;
- quarter/month and domain constraints are active after upgrade;
- application lifespan boots on the upgraded DB and is idempotent.

The old schema is created from an explicit pre-v0007 DDL snapshot — this
test never relies on create_assessment_schema (current DDL) pre-creating
the new columns, which would mask migration defects.
"""

import asyncio
from collections.abc import Iterator

import psycopg
import pytest

from app.access.repository import assign_role, create_user
from app.access.schema import create_access_schema
from app.assessment.repository import _get_gap_summary, get_assessment
from app.catalog.importer import import_catalog, resolve_workbook_dir
from app.migrations import run_migrations
from app.migrations.versions import MIGRATIONS

# Pre-v0007 DDL snapshot (master branch, v0006 era): current_level is 1–5,
# no member_priority/include_in_plan/plan_quarter/plan_month columns,
# gap.priority is NOT NULL DEFAULT '中'.
_OLD_ASSESSMENT_DDL = [
    """
    CREATE TABLE assessment (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        member_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE,
        year INT NOT NULL,
        version INT NOT NULL DEFAULT 1,
        assessment_type TEXT NOT NULL
            CHECK (assessment_type IN ('年度', '年中更新', '晋升复核')),
        status TEXT NOT NULL
            CHECK (status IN ('草稿', '待复核', '已复核', '建议调整', '已归档')),
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        submitted_at TIMESTAMPTZ,
        archived_at TIMESTAMPTZ,
        revision BIGINT NOT NULL DEFAULT 1,
        member_current_level_snapshot TEXT CHECK (
            member_current_level_snapshot IS NULL
            OR member_current_level_snapshot IN ('P4', 'P5', 'P6', 'P7', 'P8')
        ),
        member_target_level_snapshot TEXT CHECK (
            member_target_level_snapshot IS NULL
            OR member_target_level_snapshot IN ('P4', 'P5', 'P6', 'P7', 'P8')
        ),
        capability_standard_version_id BIGINT,
        assessment_scope_version TEXT,
        UNIQUE(member_id, year, version)
    )
    """,
    """
    CREATE TABLE assessment_detail (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        assessment_id BIGINT NOT NULL REFERENCES assessment(id) ON DELETE CASCADE,
        l3_code TEXT NOT NULL,
        current_level INT CHECK (
            current_level IS NULL OR current_level BETWEEN 1 AND 5
        ),
        current_level_explicitly_cleared BOOLEAN NOT NULL DEFAULT FALSE,
        target_level INT CHECK (
            target_level IS NULL OR target_level BETWEEN 1 AND 5
        ),
        standard_target_applicable BOOLEAN,
        standard_target_level INT CHECK (
            standard_target_level IS NULL
            OR standard_target_level BETWEEN 1 AND 5
        ),
        target_adjusted BOOLEAN NOT NULL DEFAULT FALSE,
        adjusted_target_level INT CHECK (
            adjusted_target_level IS NULL
            OR adjusted_target_level BETWEEN 1 AND 5
        ),
        target_adjustment_reason TEXT,
        target_snapshot_source TEXT,
        target_compatibility_error TEXT,
        gap_value INT,
        evidence_note TEXT,
        plan_candidate BOOLEAN NOT NULL DEFAULT FALSE,
        inherited_from_assessment_id BIGINT
            REFERENCES assessment(id) ON DELETE SET NULL,
        inherited_current_level INT CHECK (
            inherited_current_level IS NULL
            OR inherited_current_level BETWEEN 1 AND 5
        ),
        inherited_evidence_note TEXT,
        l3_node_id BIGINT,
        scope_type TEXT CHECK (
            scope_type IS NULL
            OR scope_type IN ('current_required', 'target_progressive')
        ),
        standard_job_level_snapshot TEXT CHECK (
            standard_job_level_snapshot IS NULL
            OR standard_job_level_snapshot IN ('P4', 'P5', 'P6', 'P7', 'P8')
        ),
        l1_code TEXT,
        l1_name TEXT,
        l2_code TEXT,
        l2_name TEXT,
        l3_name TEXT,
        CHECK (
            standard_target_applicable IS DISTINCT FROM FALSE
            OR standard_target_level IS NULL
        ),
        CHECK (
            (target_adjusted = FALSE
             AND adjusted_target_level IS NULL
             AND target_adjustment_reason IS NULL)
            OR
            (target_adjusted = TRUE
             AND standard_target_applicable = TRUE
             AND adjusted_target_level BETWEEN 1 AND 5
             AND BTRIM(target_adjustment_reason) <> '')
        ),
        UNIQUE(assessment_id, l3_code)
    )
    """,
    """
    CREATE TABLE gap (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        assessment_id BIGINT NOT NULL REFERENCES assessment(id) ON DELETE CASCADE,
        l3_code TEXT NOT NULL,
        current_level INT NOT NULL,
        target_level INT NOT NULL,
        gap_value INT NOT NULL,
        priority TEXT NOT NULL DEFAULT '中'
            CHECK (priority IN ('高', '中', '低')),
        plan_candidate BOOLEAN NOT NULL DEFAULT FALSE,
        UNIQUE(assessment_id, l3_code)
    )
    """,
    """
    CREATE TABLE assessment_review (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        assessment_id BIGINT NOT NULL REFERENCES assessment(id) ON DELETE CASCADE,
        sequence INT NOT NULL,
        buddy_id BIGINT REFERENCES tcp_user(id) ON DELETE SET NULL,
        conclusion TEXT CHECK (conclusion IN ('认可', '建议调整')),
        feedback TEXT,
        reviewed_at TIMESTAMPTZ,
        status TEXT NOT NULL CHECK (status IN ('待复核', '已闭环')),
        UNIQUE(assessment_id, sequence)
    )
    """,
]

_EXPECTED_VERSIONS = [
    "0001_standard_targets",
    "0002_assessment_inheritance_revision",
    "0003_assessment_explicit_clear",
    "0004_legacy_draft_target_repair",
    "0005_capability_standard_versioning",
    "0006_assessment_scope_snapshots",
    "0007_assessment_plan_selection",
    "0008_plan_null_constraint",
    "0009_review_plan_atomic",
    "0010_learning_execution",
    "0011_monthly_review",
    "0012_team_analytics_indexes",
    "0013_plan_item_growth_goal_nullable",
]

# Pre-v0007 planning DDL snapshot (v0006 era): plan_item.growth_goal_id is
# NOT NULL, plan_item.priority has DEFAULT '中', and none of the v0009 source
# columns exist.  v0009 must add them additively on upgrade.
_OLD_PLANNING_DDL = [
    """
    CREATE TABLE annual_growth_plan (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        member_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE,
        year INT NOT NULL,
        plan_cycle INT NOT NULL DEFAULT 12,
        status TEXT NOT NULL DEFAULT '制定中'
            CHECK (status IN ('制定中', '执行中', '已归档')),
        start_date DATE,
        end_date DATE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        UNIQUE(member_id, year)
    )
    """,
    """
    CREATE TABLE growth_goal (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gap_id BIGINT NOT NULL REFERENCES gap(id) ON DELETE CASCADE,
        annual_growth_plan_id BIGINT NOT NULL
            REFERENCES annual_growth_plan(id) ON DELETE CASCADE,
        l3_code TEXT NOT NULL,
        year INT NOT NULL,
        target_level INT NOT NULL,
        priority TEXT NOT NULL DEFAULT '中'
            CHECK (priority IN ('高', '中', '低')),
        UNIQUE(annual_growth_plan_id, l3_code)
    )
    """,
    """
    CREATE TABLE plan_item (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        annual_growth_plan_id BIGINT NOT NULL
            REFERENCES annual_growth_plan(id) ON DELETE CASCADE,
        growth_goal_id BIGINT NOT NULL REFERENCES growth_goal(id) ON DELETE CASCADE,
        l3_code TEXT NOT NULL,
        current_level INT NOT NULL,
        target_level INT NOT NULL,
        priority TEXT NOT NULL DEFAULT '中'
            CHECK (priority IN ('高', '中', '低')),
        learning_material TEXT,
        learning_task_content TEXT,
        expected_output TEXT,
        estimated_hours TEXT,
        plan_start_date DATE,
        plan_end_date DATE,
        target_month INT,
        status TEXT NOT NULL DEFAULT '未开始'
            CHECK (status IN ('未开始', '进行中', '已完成', '延期', '暂停', '取消')),
        UNIQUE(annual_growth_plan_id, l3_code),
        UNIQUE(growth_goal_id)
    )
    """,
    """
    CREATE TABLE learning_task (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        plan_item_id BIGINT NOT NULL REFERENCES plan_item(id) ON DELETE CASCADE,
        l3_code TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT '未开始'
            CHECK (status IN ('未开始', '进行中', '待 Evidence Review',
                              '已完成', '延期', '暂停', '取消')),
        actual_start_date DATE,
        actual_end_date DATE,
        actual_hours INT DEFAULT 0,
        completion_quality TEXT,
        review_conclusion TEXT,
        next_action TEXT,
        UNIQUE(plan_item_id)
    )
    """,
    # v0001-era planning schema (as built by the pre-v0010 schema helper) —
    # v0010 extends these execution tables, so a realistic v0006 database
    # must contain them in their legacy shape.
    """
    CREATE TABLE learning_progress_log (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        task_id BIGINT NOT NULL REFERENCES learning_task(id) ON DELETE CASCADE,
        record_date DATE NOT NULL,
        actual_hours INT NOT NULL CHECK (actual_hours >= 0),
        note TEXT,
        recorder_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE evidence (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        learning_task_id BIGINT NOT NULL
            REFERENCES learning_task(id) ON DELETE CASCADE,
        l3_code TEXT NOT NULL,
        version_number INT NOT NULL CHECK (version_number > 0),
        content TEXT,
        evidence_link TEXT,
        status TEXT NOT NULL DEFAULT '草稿'
            CHECK (status IN ('草稿', '待 Review', '通过', '需补充',
                              '驳回', '已归档')),
        submitted_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        UNIQUE(learning_task_id, version_number)
    )
    """,
    """
    CREATE TABLE evidence_review (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        evidence_id BIGINT NOT NULL UNIQUE
            REFERENCES evidence(id) ON DELETE CASCADE,
        buddy_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE,
        status TEXT NOT NULL DEFAULT '待 Review'
            CHECK (status IN ('待 Review', '通过', '需补充', '驳回', '已闭环')),
        conclusion TEXT CHECK (conclusion IN ('通过', '需补充', '驳回')),
        feedback TEXT,
        reviewed_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
    """,
]


def _detail_columns(connection: psycopg.Connection) -> set[str]:
    rows = connection.execute(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_name = 'assessment_detail'"
    ).fetchall()
    return {str(row[0]) for row in rows}


def _applied_versions(connection: psycopg.Connection) -> list[str]:
    rows = connection.execute(
        "SELECT version FROM schema_migration ORDER BY applied_at, version"
    ).fetchall()
    return [str(row[0]) for row in rows]


@pytest.fixture
def pre_v0007_db(connection: psycopg.Connection) -> Iterator[psycopg.Connection]:
    """A realistic database migrated only up to v0006, with legacy data."""
    with connection.transaction():
        for table in (
            "assessment_review",
            "gap",
            "assessment_detail",
            "assessment_idempotency_key",
            "assessment_draft_target_repair_audit",
            "assessment",
            "buddy_relationship",
            "tcp_session",
            "tcp_user_role",
            "tcp_role",
            "tcp_user",
        ):
            connection.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
        connection.execute("DROP TABLE IF EXISTS schema_migration CASCADE")
        connection.execute("DROP TABLE IF EXISTS capability_standard_item CASCADE")
        connection.execute(
            "DROP TABLE IF EXISTS capability_standard_target_override CASCADE"
        )
        connection.execute(
            "DROP TABLE IF EXISTS capability_standard_version_audit CASCADE"
        )
        connection.execute("DROP TABLE IF EXISTS capability_standard_version CASCADE")
    create_access_schema(connection)
    for ddl in _OLD_ASSESSMENT_DDL:
        connection.execute(ddl)
    for ddl in _OLD_PLANNING_DDL:
        connection.execute(ddl)
    import_catalog(resolve_workbook_dir(), connection)

    # Apply v0001–v0006 exactly as the runner would, nothing later.
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS schema_migration (
            version TEXT PRIMARY KEY,
            applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
        """
    )
    for version, upgrade in MIGRATIONS[:6]:
        upgrade(connection)
        connection.execute(
            "INSERT INTO schema_migration (version) VALUES (%s)", (version,)
        )

    # Legacy business data written by the pre-v0007 application.
    member_id = create_user(connection, "mig-member", "Migration Member", "secret")
    assign_role(connection, member_id, "Member")
    connection.execute(
        "UPDATE tcp_user SET current_level = 'P4', target_level = 'P5' WHERE id = %s",
        (member_id,),
    )
    connection.execute(
        """
        INSERT INTO assessment
            (member_id, year, assessment_type, status, submitted_at, archived_at)
        VALUES (%s, 2024, '年度', '已归档', NOW(), NOW())
        """,
        (member_id,),
    )
    archived_id = int(
        connection.execute(
            "SELECT id FROM assessment WHERE member_id = %s AND year = 2024",
            (member_id,),
        ).fetchone()[0]
    )
    connection.execute(
        """
        INSERT INTO assessment_detail
            (assessment_id, l3_code, current_level, target_level,
             standard_target_applicable, standard_target_level, gap_value,
             evidence_note, plan_candidate)
        VALUES (%s, 'C01.01.01', 2, 3, TRUE, 3, 1, '历史依据', TRUE)
        """,
        (archived_id,),
    )
    connection.execute(
        """
        INSERT INTO gap
            (assessment_id, l3_code, current_level, target_level, gap_value,
             priority, plan_candidate)
        VALUES (%s, 'C01.01.01', 2, 3, 1, '高', TRUE)
        """,
        (archived_id,),
    )
    # A legacy open draft with an unassessed row.
    connection.execute(
        """
        INSERT INTO assessment (member_id, year, assessment_type, status)
        VALUES (%s, 2025, '年度', '草稿')
        """,
        (member_id,),
    )
    draft_id = int(
        connection.execute(
            "SELECT id FROM assessment WHERE member_id = %s AND year = 2025",
            (member_id,),
        ).fetchone()[0]
    )
    connection.execute(
        """
        INSERT INTO assessment_detail (assessment_id, l3_code, plan_candidate)
        VALUES (%s, 'C01.01.02', FALSE)
        """,
        (draft_id,),
    )
    connection.commit()
    yield connection


def test_registry_order_covers_v0001_through_v0008() -> None:
    """The migration chain registers v0001→v0008 in order (v0007 present)."""
    assert [version for version, _ in MIGRATIONS] == _EXPECTED_VERSIONS


def test_pre_v0007_database_really_lacks_new_contract(
    pre_v0007_db: psycopg.Connection,
) -> None:
    connection = pre_v0007_db
    columns = _detail_columns(connection)
    assert "member_priority" not in columns
    assert "include_in_plan" not in columns
    assert "plan_quarter" not in columns
    assert "plan_month" not in columns
    assert _applied_versions(connection) == _EXPECTED_VERSIONS[:6]

    # Old CHECK: current_level=0 is rejected pre-v0007.
    draft_id = int(
        connection.execute("SELECT id FROM assessment WHERE year = 2025").fetchone()[0]
    )
    with pytest.raises(psycopg.errors.CheckViolation):
        with connection.transaction():
            connection.execute(
                "INSERT INTO assessment_detail (assessment_id, l3_code, "
                "current_level, plan_candidate) "
                "VALUES (%s, 'C01.01.03', 0, FALSE)",
                (draft_id,),
            )
    # gap.priority is still NOT NULL pre-v0007.
    archived_id = int(
        connection.execute("SELECT id FROM assessment WHERE year = 2024").fetchone()[0]
    )
    with pytest.raises(psycopg.errors.NotNullViolation):
        with connection.transaction():
            connection.execute(
                "INSERT INTO gap (assessment_id, l3_code, current_level, "
                "target_level, gap_value, priority, plan_candidate) "
                "VALUES (%s, 'C01.01.09', 1, 3, 2, NULL, FALSE)",
                (archived_id,),
            )
    connection.commit()


def test_upgrade_to_v0008_and_lifespan(pre_v0007_db: psycopg.Connection) -> None:
    connection = pre_v0007_db

    # ── Run the production migration runner (v0007 → latest). ─────────
    run_migrations(connection)
    connection.commit()

    # Order + run-once.
    applied = _applied_versions(connection)
    assert applied == _EXPECTED_VERSIONS
    assert len(set(applied)) == len(applied)

    # New columns exist now.
    columns = _detail_columns(connection)
    for column in (
        "member_priority",
        "include_in_plan",
        "plan_quarter",
        "plan_month",
    ):
        assert column in columns

    # ── Legacy data readable, values intact, nothing fabricated. ──────
    archived = get_assessment(
        connection,
        int(
            connection.execute(
                "SELECT id FROM assessment WHERE year = 2024"
            ).fetchone()[0]
        ),
    )
    row = next(d for d in archived["details"] if d["l3_code"] == "C01.01.01")
    assert row["current_level"] == 2
    assert row["plan_candidate"] is True  # legacy read-only value preserved
    assert row["member_priority"] is None  # NOT fabricated from gap.priority
    assert row["include_in_plan"] is None  # NOT fabricated from plan_candidate
    assert row["plan_quarter"] is None
    assert row["plan_month"] is None

    # Summary must not present legacy auto-values as member decisions.
    summary = _get_gap_summary(connection, int(archived["id"]))
    assert summary["total_gaps"] == 1
    assert summary["in_plan"] == 0
    assert summary["high_priority"] == 0
    assert summary["on_hold"] == 0

    # Legacy gap row keeps its historical priority (read-only).
    gap_row = connection.execute(
        "SELECT priority, plan_candidate FROM gap WHERE l3_code = 'C01.01.01'"
    ).fetchone()
    assert gap_row == ("高", True)

    # Legacy unassessed draft row stays NULL.
    draft = get_assessment(
        connection,
        int(
            connection.execute(
                "SELECT id FROM assessment WHERE year = 2025"
            ).fetchone()[0]
        ),
    )
    draft_row = draft["details"][0]
    assert draft_row["current_level"] is None
    assert draft_row["member_priority"] is None
    assert draft_row["include_in_plan"] is None

    # ── New constraints are active. ────────────────────────────────────
    detail_id = int(row["id"])
    # current_level=0 is legal now (0 = 未接触, distinct from NULL).
    with connection.transaction():
        connection.execute(
            "UPDATE assessment_detail SET current_level = 0 WHERE id = %s",
            (detail_id,),
        )
    # Invalid priority rejected.
    with pytest.raises(psycopg.errors.CheckViolation):
        with connection.transaction():
            connection.execute(
                "UPDATE assessment_detail SET member_priority = '无效' "
                "WHERE id = %s",
                (detail_id,),
            )
    # include_in_plan=TRUE without quarter/month rejected (v0007).
    with pytest.raises(psycopg.errors.CheckViolation):
        with connection.transaction():
            connection.execute(
                "UPDATE assessment_detail SET include_in_plan = TRUE " "WHERE id = %s",
                (detail_id,),
            )
    # include_in_plan=NULL with plan_quarter set rejected (v0008).
    with pytest.raises(psycopg.errors.CheckViolation):
        with connection.transaction():
            connection.execute(
                "UPDATE assessment_detail SET plan_quarter = 'Q1' WHERE id = %s",
                (detail_id,),
            )
    connection.commit()

    # ── Idempotent re-run. ─────────────────────────────────────────────
    run_migrations(connection)
    connection.commit()
    assert _applied_versions(connection) == _EXPECTED_VERSIONS

    # ── Full application lifespan boots on the upgraded database. ──────
    from app.main import app as fastapi_app
    from app.main import lifespan

    async def _boot() -> None:
        async with lifespan(fastapi_app):
            pass

    asyncio.run(_boot())

    # Lifespan ran migrations idempotently and left legacy data intact.
    assert _applied_versions(connection) == _EXPECTED_VERSIONS
    row_after = connection.execute(
        "SELECT current_level, member_priority, include_in_plan "
        "FROM assessment_detail WHERE id = %s",
        (detail_id,),
    ).fetchone()
    assert row_after == (0, None, None)

    # A second boot is also idempotent.
    asyncio.run(_boot())
    assert _applied_versions(connection) == _EXPECTED_VERSIONS
