import psycopg


def create_catalog_schema(connection: psycopg.Connection) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS capability_model (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL,
            version TEXT NOT NULL,
            source_workbook TEXT NOT NULL,
            source_sheet TEXT NOT NULL,
            source_row INTEGER NOT NULL
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS capability_node (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            model_id BIGINT NOT NULL REFERENCES capability_model(id) ON DELETE CASCADE,
            parent_node_id BIGINT REFERENCES capability_node(id) ON DELETE CASCADE,
            node_type TEXT NOT NULL CHECK (node_type IN ('L1', 'L2', 'L3')),
            code TEXT NOT NULL,
            name TEXT NOT NULL,
            sort_order INTEGER NOT NULL,
            l1_category TEXT,
            enabled BOOLEAN NOT NULL DEFAULT TRUE,
            p4_description TEXT,
            p5_description TEXT,
            p6_description TEXT,
            p7_description TEXT,
            p8_description TEXT,
            recommended_start_level TEXT,
            materials_text TEXT,
            expected_output TEXT,
            estimated_hours TEXT,
            source_workbook TEXT NOT NULL,
            source_sheet TEXT NOT NULL,
            source_row INTEGER NOT NULL,
            UNIQUE (model_id, code),
            CHECK (
                (node_type = 'L1' AND parent_node_id IS NULL)
                OR (node_type IN ('L2', 'L3') AND parent_node_id IS NOT NULL)
            )
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS learning_resource (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            material_code TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL,
            material_type TEXT NOT NULL,
            source_text TEXT NOT NULL,
            purpose TEXT NOT NULL,
            status TEXT NOT NULL,
            source_workbook TEXT NOT NULL,
            source_sheet TEXT NOT NULL,
            source_row INTEGER NOT NULL
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS capability_node_resource (
            node_id BIGINT NOT NULL REFERENCES capability_node(id) ON DELETE CASCADE,
            resource_id BIGINT NOT NULL
                REFERENCES learning_resource(id) ON DELETE CASCADE,
            PRIMARY KEY (node_id, resource_id)
        )
        """
    )
