import psycopg


def create_catalog_schema(connection: psycopg.Connection) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS capability_model (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL,
            version TEXT NOT NULL,
            source_workbook TEXT NOT NULL,
            source_sheet TEXT NOT NULL,
            source_row INTEGER NOT NULL
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS capability_node (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            model_id BIGINT NOT NULL REFERENCES capability_model(id) ON DELETE CASCADE,
            parent_node_id BIGINT REFERENCES capability_node(id) ON DELETE CASCADE,
            node_type TEXT NOT NULL CHECK (node_type IN ('L1', 'L2', 'L3')),
            code TEXT NOT NULL,
            name TEXT NOT NULL,
            sort_order INTEGER NOT NULL,
            l1_category TEXT,
            overview TEXT,
            enabled BOOLEAN NOT NULL DEFAULT TRUE,
            p4_description TEXT,
            p5_description TEXT,
            p6_description TEXT,
            p7_description TEXT,
            p8_description TEXT,
            recommended_start_level TEXT,
            materials_text TEXT,
            expected_output TEXT,
            estimated_hours TEXT,
            output_type TEXT,
            notes TEXT,
            source_workbook TEXT NOT NULL,
            source_sheet TEXT NOT NULL,
            source_row INTEGER NOT NULL,
            UNIQUE (model_id, code),
            CHECK (
                (node_type = 'L1' AND parent_node_id IS NULL)
                OR (node_type IN ('L2', 'L3') AND parent_node_id IS NOT NULL)
            )
        )
        """
    )
    for column in ("overview", "output_type", "notes"):
        connection.execute(
            f"ALTER TABLE capability_node ADD COLUMN IF NOT EXISTS {column} TEXT"
        )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS learning_resource (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            material_code TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL,
            material_type TEXT NOT NULL,
            source_text TEXT NOT NULL,
            purpose TEXT NOT NULL,
            status TEXT NOT NULL,
            source_workbook TEXT NOT NULL,
            source_sheet TEXT NOT NULL,
            source_row INTEGER NOT NULL
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS capability_node_resource (
            node_id BIGINT NOT NULL REFERENCES capability_node(id) ON DELETE CASCADE,
            resource_id BIGINT NOT NULL
                REFERENCES learning_resource(id) ON DELETE CASCADE,
            PRIMARY KEY (node_id, resource_id)
        )
        """
    )
    # Immutable planning source per (standard version, L3). The FK to
    # capability_standard_version and the immutability trigger are added by the
    # v0009 migration (the version table is created by migrations at startup).
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS capability_standard_planning_snapshot (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            capability_standard_version_id BIGINT NOT NULL,
            l3_node_id BIGINT NOT NULL
                REFERENCES capability_node(id) ON DELETE RESTRICT,
            l3_code TEXT NOT NULL,
            l3_name TEXT NOT NULL,
            materials_text TEXT,
            resource_snapshot JSONB NOT NULL DEFAULT '[]'::jsonb,
            expected_output TEXT,
            estimated_hours TEXT,
            output_type TEXT,
            notes TEXT,
            source_workbook TEXT,
            source_sheet TEXT,
            source_row INT,
            source_type TEXT NOT NULL
                CHECK (
                    source_type IN ('legacy_catalog_capture_v0009', 'version_publish')
                ),
            source_hash TEXT NOT NULL,
            captured_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE (capability_standard_version_id, l3_node_id)
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS capability_standard_target_override (
            node_id BIGINT NOT NULL
                REFERENCES capability_node(id) ON DELETE CASCADE,
            job_level TEXT NOT NULL
                CHECK (job_level IN ('P4', 'P5', 'P6', 'P7', 'P8')),
            target_level INT CHECK (
                target_level IS NULL OR target_level BETWEEN 1 AND 5
            ),
            PRIMARY KEY (node_id, job_level)
        )
        """
    )
    connection.execute(
        """
        CREATE OR REPLACE FUNCTION validate_capability_node_hierarchy()
        RETURNS TRIGGER
        LANGUAGE plpgsql
        AS $$
        DECLARE
            parent_type TEXT;
            parent_model_id BIGINT;
        BEGIN
            IF NEW.node_type = 'L1' THEN
                IF NEW.parent_node_id IS NOT NULL THEN
                    RAISE EXCEPTION 'L1 capability nodes cannot have a parent';
                END IF;
            ELSE
                SELECT node_type, model_id
                INTO parent_type, parent_model_id
                FROM capability_node
                WHERE id = NEW.parent_node_id;

                IF NOT FOUND
                   OR parent_model_id <> NEW.model_id
                   OR (NEW.node_type = 'L2' AND parent_type <> 'L1')
                   OR (NEW.node_type = 'L3' AND parent_type <> 'L2') THEN
                    RAISE EXCEPTION 'invalid capability node parent hierarchy';
                END IF;
            END IF;

            IF EXISTS (
                SELECT 1
                FROM capability_node AS child
                WHERE child.parent_node_id = NEW.id
                  AND (
                      child.model_id <> NEW.model_id
                      OR (child.node_type = 'L2' AND NEW.node_type <> 'L1')
                      OR (child.node_type = 'L3' AND NEW.node_type <> 'L2')
                  )
            ) THEN
                RAISE EXCEPTION 'capability node update would invalidate a child';
            END IF;

            IF NEW.node_type <> 'L3' AND EXISTS (
                SELECT 1
                FROM capability_node_resource
                WHERE node_id = NEW.id
            ) THEN
                RAISE EXCEPTION 'only L3 capability nodes can link resources';
            END IF;

            RETURN NEW;
        END;
        $$
        """
    )
    connection.execute(
        """
        CREATE OR REPLACE FUNCTION validate_capability_node_resource()
        RETURNS TRIGGER
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF (
                SELECT node_type FROM capability_node WHERE id = NEW.node_id
            ) <> 'L3' THEN
                RAISE EXCEPTION 'only L3 capability nodes can link resources';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    connection.execute(
        """
        DROP TRIGGER IF EXISTS capability_node_hierarchy_trigger
        ON capability_node
        """
    )
    connection.execute(
        """
        CREATE TRIGGER capability_node_hierarchy_trigger
        BEFORE INSERT OR UPDATE OF node_type, parent_node_id, model_id
        ON capability_node
        FOR EACH ROW EXECUTE FUNCTION validate_capability_node_hierarchy()
        """
    )
    connection.execute(
        """
        DROP TRIGGER IF EXISTS capability_node_resource_type_trigger
        ON capability_node_resource
        """
    )
    connection.execute(
        """
        CREATE TRIGGER capability_node_resource_type_trigger
        BEFORE INSERT OR UPDATE OF node_id
        ON capability_node_resource
        FOR EACH ROW EXECUTE FUNCTION validate_capability_node_resource()
        """
    )
