import type { Assessment, AssessmentDetail, GapSummary } from '../assessment'
import { isMockEnabled as mockOn } from './memberDashboard'

export function isMockEnabled(): boolean {
  return mockOn()
}

const ALL: AssessmentDetail[] = [
  // P01 — 2 filled, 1 empty, mix of gaps
  {
    id: 1,
    l3_code: 'P01.01.01',
    l3_name: '数据管道基础',
    current_level: 2,
    target_level: 4,
    gap_value: 2,
    evidence_note: '已完成数据口径梳理，产出数据血缘文档',
    plan_candidate: true,
    recommended_start_level: 'P4',
    l1_code: 'P01',
    l1_name: '数据基础设施',
  },
  {
    id: 2,
    l3_code: 'P01.01.02',
    l3_name: '文件命名规范',
    current_level: 3,
    target_level: 5,
    gap_value: 2,
    evidence_note: '',
    plan_candidate: false,
    recommended_start_level: 'P4',
    l1_code: 'P01',
    l1_name: '数据基础设施',
  },
  {
    id: 3,
    l3_code: 'P01.02.01',
    l3_name: '数据质量监控',
    current_level: null,
    target_level: null,
    gap_value: 0,
    evidence_note: '',
    plan_candidate: false,
    recommended_start_level: 'P5',
    l1_code: 'P01',
    l1_name: '数据基础设施',
  },
  // P02 — 1 filled, high gap
  {
    id: 4,
    l3_code: 'P02.01.01',
    l3_name: '模型部署流程',
    current_level: 1,
    target_level: 4,
    gap_value: 3,
    evidence_note: '阅读了 MLOps 指南，了解了 CI/CD 流水线概念',
    plan_candidate: true,
    recommended_start_level: 'P4–P5',
    l1_code: 'P02',
    l1_name: 'AI Infra / Agent',
  },
  {
    id: 5,
    l3_code: 'P02.01.02',
    l3_name: 'Agent 工具链搭建',
    current_level: null,
    target_level: null,
    gap_value: 0,
    evidence_note: '',
    plan_candidate: false,
    recommended_start_level: 'P5',
    l1_code: 'P02',
    l1_name: 'AI Infra / Agent',
  },
  // P03 — 1 filled
  {
    id: 6,
    l3_code: 'P03.01.01',
    l3_name: '代码审查规范',
    current_level: 3,
    target_level: 5,
    gap_value: 2,
    evidence_note: '',
    plan_candidate: true,
    recommended_start_level: 'P4',
    l1_code: 'P03',
    l1_name: '工程编码',
  },
  {
    id: 7,
    l3_code: 'P03.02.01',
    l3_name: '单元测试实践',
    current_level: 2,
    target_level: 4,
    gap_value: 2,
    evidence_note: '',
    plan_candidate: true,
    recommended_start_level: 'P4',
    l1_code: 'P03',
    l1_name: '工程编码',
  },
  // C01 — 2 filled
  {
    id: 8,
    l3_code: 'C01.01.01',
    l3_name: '常用办公工具基础',
    current_level: 4,
    target_level: 5,
    gap_value: 1,
    evidence_note: '熟练使用 Office 套件和协作平台',
    plan_candidate: false,
    recommended_start_level: 'P4',
    l1_code: 'C01',
    l1_name: '基本办公能力',
  },
  {
    id: 9,
    l3_code: 'C01.02.01',
    l3_name: '会议纪要与操作记录',
    current_level: null,
    target_level: null,
    gap_value: 0,
    evidence_note: '',
    plan_candidate: false,
    recommended_start_level: 'P4',
    l1_code: 'C01',
    l1_name: '基本办公能力',
  },
  // C02 — 1 filled, high gap
  {
    id: 10,
    l3_code: 'C02.01.01',
    l3_name: '技术方案写作',
    current_level: 1,
    target_level: 5,
    gap_value: 4,
    evidence_note: '写完了一份 API 设计文档',
    plan_candidate: true,
    recommended_start_level: 'P5–P6',
    l1_code: 'C02',
    l1_name: '沟通协作',
  },
  {
    id: 11,
    l3_code: 'C02.02.01',
    l3_name: '跨团队协作沟通',
    current_level: null,
    target_level: null,
    gap_value: 0,
    evidence_note: '',
    plan_candidate: false,
    recommended_start_level: 'P5',
    l1_code: 'C02',
    l1_name: '沟通协作',
  },
  // C03 — 1 filled, low gap
  {
    id: 12,
    l3_code: 'C03.01.01',
    l3_name: '新技术调研方法',
    current_level: 4,
    target_level: 4,
    gap_value: 0,
    evidence_note: '定期阅读技术博客，完成 3 篇调研报告',
    plan_candidate: true,
    recommended_start_level: 'P5',
    l1_code: 'C03',
    l1_name: '学习创新',
  },
  {
    id: 13,
    l3_code: 'C03.02.01',
    l3_name: '知识分享输出',
    current_level: null,
    target_level: null,
    gap_value: 0,
    evidence_note: '',
    plan_candidate: false,
    recommended_start_level: 'P6',
    l1_code: 'C03',
    l1_name: '学习创新',
  },
]

const gapSummary: GapSummary = {
  total_gaps: 7,
  avg_gap: 2.3,
  high_priority: 2,
  medium_priority: 3,
  low_priority: 2,
}

export const mockAssessment: Assessment = {
  id: 100,
  member_id: 1,
  year: 2026,
  version: 1,
  assessment_type: '年度',
  status: '草稿',
  created_at: '2026-01-15T00:00:00Z',
  submitted_at: null,
  archived_at: null,
  details: ALL,
  gap_summary: gapSummary,
}

export const mockAssessmentSubmitted: Assessment = {
  ...mockAssessment,
  status: '待复核',
  submitted_at: '2026-07-19T00:00:00Z',
  gap_summary: gapSummary,
}
