"""v0009: Buddy Review atomic plan generation.

Additive, forward-only. Adds:

- ``capability_standard_planning_snapshot`` — immutable planning source per
  (version, L3), with a DB trigger blocking INSERT/UPDATE/DELETE once the
  version is published/archived (enabled only after the legacy backfill);
- ``legacy_catalog_capture_v0009`` backfill for pre-v0009 published/archived
  versions (explicitly marked as a one-time capture, never claimed to be the
  original publish-time snapshot);
- ``annual_growth_plan`` source columns (source_assessment_id, planning_source_type)
  with a partial unique index on the first-source assessment;
- ``plan_item`` full source snapshot columns, ``priority`` default removal,
  ``created_at``, CHECKs and a partial unique index on source_assessment_detail_id;
- ``assessment_review.reviewed_by_buddy_id`` (actual closer, legacy NULL ok);
- ``buddy_relationship`` canonical ``effective_date``/``expiry_date`` with a
  sync trigger (legacy columns cannot drift), an interval-overlap guard for
  primary relationships, and a second partial unique index;
- ``annual_plan_change_proposal`` + ``annual_plan_change_proposal_detail``
  (subsequent-assessment change proposals bound to the target plan), plus a
  pair of triggers forbidding the proposal source from being the target
  plan's first-source assessment (in both directions, INSERT and UPDATE);
- ``review_idempotency_key`` keyed by (buddy_id, idempotency_key).

No columns, tables or rows are removed or rewritten; historical data stays
readable.
"""

import json

import psycopg

from app.catalog.standard_versions import planning_snapshot_hash

# ruff: noqa: E501


def _add_fk(
    connection: psycopg.Connection,
    table: str,
    constraint: str,
    definition: str,
) -> None:
    connection.execute(
        f"""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = '{table}'::regclass AND conname = '{constraint}'
            ) THEN
                ALTER TABLE {table} ADD CONSTRAINT {constraint} {definition};
            END IF;
        END $$
        """
    )


def _add_check(
    connection: psycopg.Connection,
    table: str,
    constraint: str,
    expression: str,
) -> None:
    connection.execute(
        f"""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = '{table}'::regclass AND conname = '{constraint}'
            ) THEN
                ALTER TABLE {table} ADD CONSTRAINT {constraint} CHECK ({expression});
            END IF;
        END $$
        """
    )


def _create_planning_snapshot(connection: psycopg.Connection) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS capability_standard_planning_snapshot (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            capability_standard_version_id BIGINT NOT NULL,
            l3_node_id BIGINT NOT NULL REFERENCES capability_node(id) ON DELETE RESTRICT,
            l3_code TEXT NOT NULL,
            l3_name TEXT NOT NULL,
            materials_text TEXT,
            resource_snapshot JSONB NOT NULL DEFAULT '[]'::jsonb,
            expected_output TEXT,
            estimated_hours TEXT,
            output_type TEXT,
            notes TEXT,
            source_workbook TEXT,
            source_sheet TEXT,
            source_row INT,
            source_type TEXT NOT NULL
                CHECK (source_type IN ('legacy_catalog_capture_v0009', 'version_publish')),
            source_hash TEXT NOT NULL,
            captured_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE (capability_standard_version_id, l3_node_id)
        )
        """
    )
    # On fresh databases the table already exists (created by
    # create_catalog_schema without the FK, because the version table is created
    # later by migrations); on upgraded databases it is created here with the FK
    # inline.  The explicit FK below covers the fresh path idempotently.
    _add_fk(
        connection,
        "capability_standard_planning_snapshot",
        "planning_snapshot_version_fk",
        "FOREIGN KEY (capability_standard_version_id) "
        "REFERENCES capability_standard_version(id) ON DELETE RESTRICT",
    )
    # P1-4: composite key (id, version, node) so plan_item and proposal_detail
    # can FK the exact (snapshot, version, node) triple.
    connection.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uniq_snapshot_id_version_node
        ON capability_standard_planning_snapshot (
            id, capability_standard_version_id, l3_node_id
        )
        """
    )


def _enable_planning_snapshot_immutability(connection: psycopg.Connection) -> None:
    """P1-1: DB-level immutability for published/archived planning snapshots.

    Runs *after* the legacy backfill: the backfill inserts snapshots for
    already-published/archived versions, so the trigger must not exist yet.
    INSERT/UPDATE/DELETE all consult the version status; NEW is used for
    INSERT, OLD for UPDATE/DELETE (the version id must never change).
    """
    connection.execute(
        """
        CREATE OR REPLACE FUNCTION guard_planning_snapshot_immutable()
        RETURNS TRIGGER AS $$
        DECLARE
            v_status TEXT;
        BEGIN
            IF TG_OP = 'INSERT' THEN
                -- Only the NEW version's status matters: appending a snapshot
                -- to a published/archived version is always rejected.
                SELECT status INTO v_status
                FROM capability_standard_version
                WHERE id = NEW.capability_standard_version_id;
                IF v_status IN ('已发布', '已归档') THEN
                    RAISE EXCEPTION
                        'planning snapshot is immutable for published/archived versions'
                        USING ERRCODE = 'P0001';
                END IF;
                RETURN NEW;
            ELSIF TG_OP = 'UPDATE' THEN
                -- Identity fields (version, node) never drift: a snapshot row
                -- belongs to exactly one (version, node) forever, so it can
                -- never be UPDATE-moved into a published/archived version or
                -- onto another node.
                IF NEW.capability_standard_version_id IS DISTINCT FROM OLD.capability_standard_version_id
                   OR NEW.l3_node_id IS DISTINCT FROM OLD.l3_node_id THEN
                    RAISE EXCEPTION
                        'planning snapshot identity fields are immutable'
                        USING ERRCODE = 'P0001';
                END IF;
                -- Content is frozen whenever either the old or the new version
                -- is published/archived (the version status itself cannot
                -- change here because the identity check above forbids it).
                SELECT status INTO v_status
                FROM capability_standard_version
                WHERE id = OLD.capability_standard_version_id;
                IF v_status IN ('已发布', '已归档') THEN
                    RAISE EXCEPTION
                        'planning snapshot is immutable for published/archived versions'
                        USING ERRCODE = 'P0001';
                END IF;
                RETURN NEW;
            ELSE
                -- DELETE: the snapshot is frozen once its version is
                -- published/archived.
                SELECT status INTO v_status
                FROM capability_standard_version
                WHERE id = OLD.capability_standard_version_id;
                IF v_status IN ('已发布', '已归档') THEN
                    RAISE EXCEPTION
                        'planning snapshot is immutable for published/archived versions'
                        USING ERRCODE = 'P0001';
                END IF;
                RETURN OLD;
            END IF;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    connection.execute(
        """
        DROP TRIGGER IF EXISTS trg_planning_snapshot_immutable
        ON capability_standard_planning_snapshot
        """
    )
    connection.execute(
        """
        CREATE TRIGGER trg_planning_snapshot_immutable
        BEFORE INSERT OR UPDATE OR DELETE ON capability_standard_planning_snapshot
        FOR EACH ROW EXECUTE FUNCTION guard_planning_snapshot_immutable()
        """
    )


def _capture_legacy_planning_snapshots(connection: psycopg.Connection) -> None:
    """One-time compatibility capture for pre-v0009 published/archived versions.

    Values are taken from the current catalog at migration time and are
    explicitly tagged ``legacy_catalog_capture_v0009`` with the capture time and
    a hash over every frozen fact — never claimed to be the original
    publish-time snapshot.
    """
    versions = connection.execute(
        """
        SELECT id FROM capability_standard_version
        WHERE status IN ('已发布', '已归档')
        ORDER BY id
        """
    ).fetchall()
    for (version_id,) in versions:
        node_ids = connection.execute(
            """
            SELECT DISTINCT l3_node_id FROM capability_standard_item
            WHERE version_id = %s ORDER BY l3_node_id
            """,
            (version_id,),
        ).fetchall()
        for (node_id,) in node_ids:
            existing = connection.execute(
                """
                SELECT 1 FROM capability_standard_planning_snapshot
                WHERE capability_standard_version_id = %s AND l3_node_id = %s
                """,
                (version_id, node_id),
            ).fetchone()
            if existing is not None:
                continue
            row = connection.execute(
                """
                SELECT n.code, n.name, n.materials_text, n.expected_output,
                       n.estimated_hours, n.output_type, n.notes,
                       n.source_workbook, n.source_sheet, n.source_row
                FROM capability_node n
                WHERE n.id = %s AND n.node_type = 'L3'
                """,
                (node_id,),
            ).fetchone()
            if row is None:
                # Node no longer exists in the catalog: nothing to capture.
                continue
            resources = [
                {
                    "code": str(r[0]),
                    "name": str(r[1]),
                    "resource_type": str(r[2]),
                    "source": str(r[3]),
                    "purpose": str(r[4]),
                    "status": str(r[5]),
                }
                for r in connection.execute(
                    """
                    SELECT lr.material_code, lr.name, lr.material_type,
                           lr.source_text, lr.purpose, lr.status
                    FROM capability_node_resource cnr
                    JOIN learning_resource lr ON lr.id = cnr.resource_id
                    WHERE cnr.node_id = %s
                    ORDER BY lr.material_code
                    """,
                    (node_id,),
                ).fetchall()
            ]
            source_hash = planning_snapshot_hash(
                l3_node_id=int(node_id),
                l3_code=str(row[0]),
                l3_name=str(row[1]),
                materials_text=row[2],
                resources=resources,
                expected_output=row[3],
                estimated_hours=row[4],
                output_type=row[5],
                notes=row[6],
                source_workbook=row[7],
                source_sheet=row[8],
                source_row=row[9],
                source_type="legacy_catalog_capture_v0009",
            )
            connection.execute(
                """
                INSERT INTO capability_standard_planning_snapshot (
                    capability_standard_version_id, l3_node_id, l3_code, l3_name,
                    materials_text, resource_snapshot, expected_output,
                    estimated_hours, output_type, notes, source_workbook,
                    source_sheet, source_row, source_type, source_hash, captured_at
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, NOW())
                """,
                (
                    version_id,
                    node_id,
                    row[0],
                    row[1],
                    row[2],
                    json.dumps(resources, ensure_ascii=False),
                    row[3],
                    row[4],
                    row[5],
                    row[6],
                    row[7],
                    row[8],
                    row[9],
                    "legacy_catalog_capture_v0009",
                    source_hash,
                ),
            )


def _extend_annual_growth_plan(connection: psycopg.Connection) -> None:
    connection.execute(
        "ALTER TABLE annual_growth_plan ADD COLUMN IF NOT EXISTS source_assessment_id BIGINT"
    )
    connection.execute(
        "ALTER TABLE annual_growth_plan ADD COLUMN IF NOT EXISTS planning_source_type TEXT"
    )
    _add_fk(
        connection,
        "annual_growth_plan",
        "annual_growth_plan_source_assessment_fk",
        "FOREIGN KEY (source_assessment_id) REFERENCES assessment(id) ON DELETE RESTRICT",
    )
    _add_check(
        connection,
        "annual_growth_plan",
        "annual_growth_plan_source_type_check",
        "planning_source_type IS NULL OR planning_source_type IN ('assessment_approval')",
    )
    # P1-A (3rd review): the provenance discriminator and the source identity
    # travel as a pair.  A source id can never exist without the
    # assessment_approval marker, so a modern row can never be downgraded to
    # the legacy NULL branch while keeping (or clearing) its source.  Legacy
    # rows (both NULL) stay untouched.
    _add_check(
        connection,
        "annual_growth_plan",
        "annual_growth_plan_source_pairing_check",
        "source_assessment_id IS NULL OR planning_source_type = 'assessment_approval'",
    )
    connection.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uniq_plan_first_source_assessment
        ON annual_growth_plan(source_assessment_id)
        WHERE source_assessment_id IS NOT NULL
        """
    )
    # P1-4: composite keys so proposals can FK (member, year, plan) and
    # (member, year, assessment) exactly — the proposal must point at the
    # member's own plan/assessment for that year.
    connection.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uniq_annual_growth_plan_member_year_id
        ON annual_growth_plan (member_id, year, id)
        """
    )
    connection.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uniq_assessment_member_year_id
        ON assessment (member_id, year, id)
        """
    )
    # P1-3 (2nd review): the plan's source assessment must belong to the same
    # member/year as the plan itself — the DB, not just the repository, is the
    # last line.  MATCH SIMPLE lets legacy plans (NULL source) pass untouched.
    _add_fk(
        connection,
        "annual_growth_plan",
        "plan_source_assessment_member_year_fk",
        "FOREIGN KEY (member_id, year, source_assessment_id) "
        "REFERENCES assessment (member_id, year, id)",
    )
    # P1-3: plan items are bound to (plan, source assessment) so a plan item
    # can never point at a different assessment than its plan (and therefore
    # never at another member's/year's assessment).  NULL sources (legacy)
    # are exempt via MATCH SIMPLE.
    connection.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uniq_annual_growth_plan_id_source
        ON annual_growth_plan (id, source_assessment_id)
        """
    )


def _extend_plan_item(connection: psycopg.Connection) -> None:
    for definition in (
        "source_assessment_id BIGINT",
        "source_assessment_detail_id BIGINT",
        "capability_standard_version_id BIGINT",
        "planning_snapshot_id BIGINT",
        "l3_node_id BIGINT",
        "l1_code TEXT",
        "l1_name TEXT",
        "l2_code TEXT",
        "l2_name TEXT",
        "l3_name TEXT",
        "scope_type TEXT",
        "standard_target_level INT",
        "adjusted_target_level INT",
        "effective_target_level INT",
        "standard_job_level_snapshot TEXT",
        "member_current_level_snapshot TEXT",
        "member_target_level_snapshot TEXT",
        "plan_quarter TEXT",
        "plan_month INT",
        "planning_source_type TEXT",
        "assessment_revision BIGINT",
        "gap_value INT",
        "include_in_plan BOOLEAN",
        "created_at TIMESTAMPTZ",
    ):
        connection.execute(
            f"ALTER TABLE plan_item ADD COLUMN IF NOT EXISTS {definition}"
        )
    connection.execute(
        "UPDATE plan_item SET created_at = NOW() WHERE created_at IS NULL"
    )
    connection.execute(
        "ALTER TABLE plan_item ALTER COLUMN created_at SET DEFAULT NOW()"
    )
    connection.execute("ALTER TABLE plan_item ALTER COLUMN created_at SET NOT NULL")
    # Old flow no longer gets a silent "中" default: members decide priority.
    connection.execute("ALTER TABLE plan_item ALTER COLUMN priority DROP DEFAULT")
    # P1-4: composite key on assessment_detail so plan_item can FK the exact
    # (detail, assessment, node) triple — a source detail can never belong to
    # another assessment or point at a different node.
    connection.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uniq_assessment_detail_id_assessment_node
        ON assessment_detail (id, assessment_id, l3_node_id)
        """
    )
    for constraint, definition in (
        (
            "plan_item_source_assessment_fk",
            "FOREIGN KEY (source_assessment_id) REFERENCES assessment(id) ON DELETE RESTRICT",
        ),
        (
            "plan_item_source_detail_fk",
            "FOREIGN KEY (source_assessment_detail_id) REFERENCES assessment_detail(id) ON DELETE RESTRICT",
        ),
        (
            "plan_item_standard_version_fk",
            "FOREIGN KEY (capability_standard_version_id) REFERENCES capability_standard_version(id) ON DELETE RESTRICT",
        ),
        (
            "plan_item_planning_snapshot_fk",
            "FOREIGN KEY (planning_snapshot_id) REFERENCES capability_standard_planning_snapshot(id) ON DELETE RESTRICT",
        ),
        (
            "plan_item_source_detail_assessment_node_fk",
            "FOREIGN KEY (source_assessment_detail_id, source_assessment_id, l3_node_id) "
            "REFERENCES assessment_detail(id, assessment_id, l3_node_id)",
        ),
        (
            "plan_item_snapshot_version_node_fk",
            "FOREIGN KEY (planning_snapshot_id, capability_standard_version_id, l3_node_id) "
            "REFERENCES capability_standard_planning_snapshot(id, capability_standard_version_id, l3_node_id)",
        ),
        (
            "plan_item_plan_source_fk",
            "FOREIGN KEY (annual_growth_plan_id, source_assessment_id) "
            "REFERENCES annual_growth_plan (id, source_assessment_id)",
        ),
    ):
        _add_fk(connection, "plan_item", constraint, definition)
    for constraint, expression in (
        (
            "plan_item_scope_type_check",
            "scope_type IS NULL OR scope_type IN ('current_required', 'target_progressive')",
        ),
        (
            "plan_item_standard_target_check",
            "standard_target_level IS NULL OR standard_target_level BETWEEN 1 AND 5",
        ),
        (
            "plan_item_adjusted_target_check",
            "adjusted_target_level IS NULL OR adjusted_target_level BETWEEN 1 AND 5",
        ),
        (
            "plan_item_effective_target_check",
            "effective_target_level IS NULL OR effective_target_level BETWEEN 1 AND 5",
        ),
        (
            "plan_item_job_level_snapshot_check",
            "standard_job_level_snapshot IS NULL OR standard_job_level_snapshot IN ('P4','P5','P6','P7','P8')",
        ),
        (
            "plan_item_member_level_snapshot_check",
            "(member_current_level_snapshot IS NULL OR member_current_level_snapshot IN ('P4','P5','P6','P7','P8'))"
            " AND (member_target_level_snapshot IS NULL OR member_target_level_snapshot IN ('P4','P5','P6','P7','P8'))",
        ),
        (
            "plan_item_quarter_check",
            "plan_quarter IS NULL OR plan_quarter IN ('Q1','Q2','Q3','Q4')",
        ),
        (
            "plan_item_month_check",
            "plan_month IS NULL OR plan_month BETWEEN 1 AND 12",
        ),
        (
            "plan_item_quarter_month_consistency",
            "plan_quarter IS NULL OR plan_month IS NULL"
            " OR (plan_quarter = 'Q1' AND plan_month BETWEEN 1 AND 3)"
            " OR (plan_quarter = 'Q2' AND plan_month BETWEEN 4 AND 6)"
            " OR (plan_quarter = 'Q3' AND plan_month BETWEEN 7 AND 9)"
            " OR (plan_quarter = 'Q4' AND plan_month BETWEEN 10 AND 12)",
        ),
        (
            "plan_item_source_type_check",
            "planning_source_type IS NULL OR planning_source_type IN ('assessment_approval')",
        ),
        (
            "plan_item_gap_value_check",
            "gap_value IS NULL OR gap_value >= 0",
        ),
    ):
        _add_check(connection, "plan_item", constraint, expression)
    # The completeness contract was tightened (P1-4/P1-2 2nd review): drop any
    # earlier definition of the guard so upgraded databases get the strong
    # version, then add it.  The 2nd-review contract adds scope_type, the
    # member level snapshots and the effective-target consistency rule
    # (effective is the adjusted target when adjusted, else the standard).
    connection.execute(
        "ALTER TABLE plan_item "
        "DROP CONSTRAINT IF EXISTS plan_item_approval_completeness"
    )
    _add_check(
        connection,
        "plan_item",
        "plan_item_approval_completeness",
        "planning_source_type IS DISTINCT FROM 'assessment_approval'"
        " OR ("
        "include_in_plan IS TRUE"
        " AND priority IS NOT NULL AND priority IN ('高', '中', '低')"
        " AND source_assessment_id IS NOT NULL"
        " AND source_assessment_detail_id IS NOT NULL"
        " AND capability_standard_version_id IS NOT NULL"
        " AND planning_snapshot_id IS NOT NULL"
        " AND l3_node_id IS NOT NULL"
        " AND l1_code IS NOT NULL AND l1_name IS NOT NULL"
        " AND l2_code IS NOT NULL AND l2_name IS NOT NULL"
        " AND l3_code IS NOT NULL AND l3_name IS NOT NULL"
        " AND scope_type IS NOT NULL"
        " AND standard_job_level_snapshot IS NOT NULL"
        " AND member_current_level_snapshot IS NOT NULL"
        " AND member_target_level_snapshot IS NOT NULL"
        " AND assessment_revision IS NOT NULL"
        " AND target_level = effective_target_level"
        " AND standard_target_level IS NOT NULL"
        " AND effective_target_level IS NOT NULL"
        " AND gap_value IS NOT NULL"
        " AND plan_quarter IS NOT NULL AND plan_month IS NOT NULL"
        " AND ("
        "   (adjusted_target_level IS NOT NULL"
        "    AND effective_target_level = adjusted_target_level)"
        "   OR"
        "   (adjusted_target_level IS NULL"
        "    AND effective_target_level = standard_target_level)"
        " )"
        ")",
    )
    connection.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uniq_plan_item_source_detail
        ON plan_item(source_assessment_detail_id)
        WHERE source_assessment_detail_id IS NOT NULL
        """
    )


def _extend_assessment_review(connection: psycopg.Connection) -> None:
    connection.execute(
        "ALTER TABLE assessment_review ADD COLUMN IF NOT EXISTS reviewed_by_buddy_id BIGINT"
    )
    _add_fk(
        connection,
        "assessment_review",
        "assessment_review_reviewed_by_fk",
        "FOREIGN KEY (reviewed_by_buddy_id) REFERENCES tcp_user(id) ON DELETE SET NULL",
    )


def _extend_buddy_relationship(connection: psycopg.Connection) -> None:
    connection.execute(
        "ALTER TABLE buddy_relationship ADD COLUMN IF NOT EXISTS effective_date DATE"
    )
    connection.execute(
        "ALTER TABLE buddy_relationship ADD COLUMN IF NOT EXISTS expiry_date DATE"
    )
    connection.execute(
        """
        UPDATE buddy_relationship
        SET effective_date = COALESCE(effective_from, CURRENT_DATE),
            expiry_date = effective_to
        WHERE effective_date IS NULL
        """
    )
    # effective_date is NOT NULL from this point on (idempotent guard below).
    connection.execute(
        """
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'buddy_relationship'
                  AND column_name = 'effective_date'
                  AND is_nullable = 'YES'
            ) THEN
                ALTER TABLE buddy_relationship ALTER COLUMN effective_date SET NOT NULL;
            END IF;
        END $$
        """
    )
    # Canonical dates are the single source of truth; legacy columns are synced
    # by the trigger so the two pairs can never drift.
    connection.execute(
        """
        CREATE OR REPLACE FUNCTION sync_buddy_relationship_dates()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.effective_from := NEW.effective_date;
            NEW.effective_to := NEW.expiry_date;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    connection.execute(
        """
        DROP TRIGGER IF EXISTS trg_sync_buddy_relationship_dates
        ON buddy_relationship
        """
    )
    connection.execute(
        """
        CREATE TRIGGER trg_sync_buddy_relationship_dates
        BEFORE INSERT OR UPDATE ON buddy_relationship
        FOR EACH ROW EXECUTE FUNCTION sync_buddy_relationship_dates()
        """
    )
    # Interval-overlap guard: a member has at most one primary relationship
    # whose [effective_date, expiry_date] range overlaps any other's (open-ended
    # ranges count as infinite).  Adjacent ranges (expiry + 1 day = next start)
    # are allowed.
    connection.execute(
        """
        CREATE OR REPLACE FUNCTION guard_buddy_primary_overlap()
        RETURNS TRIGGER AS $$
        DECLARE
            other_id BIGINT;
        BEGIN
            IF NOT NEW.is_primary THEN
                RETURN NEW;
            END IF;
            SELECT id INTO other_id
            FROM buddy_relationship
            WHERE member_id = NEW.member_id
              AND is_primary = TRUE
              AND id <> NEW.id
              AND NEW.effective_date <= COALESCE(expiry_date, DATE '9999-12-31')
              AND COALESCE(effective_date, DATE '0001-01-01')
                  <= COALESCE(NEW.expiry_date, DATE '9999-12-31')
            LIMIT 1;
            IF other_id IS NOT NULL THEN
                RAISE EXCEPTION
                    'primary buddy relationship overlaps an existing range'
                    USING ERRCODE = 'P0001';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    connection.execute(
        """
        DROP TRIGGER IF EXISTS trg_buddy_primary_overlap
        ON buddy_relationship
        """
    )
    connection.execute(
        """
        CREATE TRIGGER trg_buddy_primary_overlap
        BEFORE INSERT OR UPDATE ON buddy_relationship
        FOR EACH ROW EXECUTE FUNCTION guard_buddy_primary_overlap()
        """
    )
    # Concurrent-creation last line: at most one open-ended primary per member.
    connection.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uniq_active_primary_buddy_v2
        ON buddy_relationship(member_id)
        WHERE is_primary = TRUE AND expiry_date IS NULL
        """
    )


def _create_change_proposal_tables(connection: psycopg.Connection) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS annual_plan_change_proposal (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            member_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE RESTRICT,
            year INT NOT NULL,
            source_assessment_id BIGINT NOT NULL
                REFERENCES assessment(id) ON DELETE RESTRICT,
            target_annual_growth_plan_id BIGINT NOT NULL
                REFERENCES annual_growth_plan(id) ON DELETE RESTRICT,
            status TEXT NOT NULL DEFAULT '待处理'
                CHECK (status IN ('待处理')),
            created_by BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE RESTRICT,
            summary JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE (source_assessment_id),
            CONSTRAINT proposal_id_source_unique
                UNIQUE (id, source_assessment_id),
            CONSTRAINT proposal_target_plan_member_year_fk
                FOREIGN KEY (member_id, year, target_annual_growth_plan_id)
                REFERENCES annual_growth_plan (member_id, year, id),
            CONSTRAINT proposal_source_assessment_member_year_fk
                FOREIGN KEY (member_id, year, source_assessment_id)
                REFERENCES assessment (member_id, year, id)
        )
        """
    )
    # P1-4: the proposal must point at the member's own plan and assessment
    # for that year (idempotent for databases where the table already exists).
    _add_fk(
        connection,
        "annual_plan_change_proposal",
        "proposal_target_plan_member_year_fk",
        "FOREIGN KEY (member_id, year, target_annual_growth_plan_id) "
        "REFERENCES annual_growth_plan (member_id, year, id)",
    )
    _add_fk(
        connection,
        "annual_plan_change_proposal",
        "proposal_source_assessment_member_year_fk",
        "FOREIGN KEY (member_id, year, source_assessment_id) "
        "REFERENCES assessment (member_id, year, id)",
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS annual_plan_change_proposal_detail (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            proposal_id BIGINT NOT NULL
                REFERENCES annual_plan_change_proposal(id) ON DELETE CASCADE,
            source_assessment_detail_id BIGINT NOT NULL
                REFERENCES assessment_detail(id) ON DELETE RESTRICT,
            assessment_id BIGINT NOT NULL,
            l3_node_id BIGINT NOT NULL,
            l1_code TEXT NOT NULL,
            l1_name TEXT NOT NULL,
            l2_code TEXT NOT NULL,
            l2_name TEXT NOT NULL,
            l3_code TEXT NOT NULL,
            l3_name TEXT NOT NULL,
            scope_type TEXT CHECK (
                scope_type IS NULL
                OR scope_type IN ('current_required', 'target_progressive')
            ),
            current_level INT CHECK (current_level IS NULL OR current_level BETWEEN 0 AND 5),
            standard_target_level INT CHECK (
                standard_target_level IS NULL OR standard_target_level BETWEEN 1 AND 5
            ),
            adjusted_target_level INT CHECK (
                adjusted_target_level IS NULL OR adjusted_target_level BETWEEN 1 AND 5
            ),
            effective_target_level INT CHECK (
                effective_target_level IS NULL OR effective_target_level BETWEEN 1 AND 5
            ),
            gap_value INT CHECK (gap_value IS NULL OR gap_value >= 0),
            member_priority TEXT CHECK (
                member_priority IS NULL OR member_priority IN ('高', '中', '低', '暂缓')
            ),
            include_in_plan BOOLEAN,
            plan_quarter TEXT CHECK (
                plan_quarter IS NULL OR plan_quarter IN ('Q1', 'Q2', 'Q3', 'Q4')
            ),
            plan_month INT CHECK (plan_month IS NULL OR plan_month BETWEEN 1 AND 12),
            standard_job_level_snapshot TEXT CHECK (
                standard_job_level_snapshot IS NULL
                OR standard_job_level_snapshot IN ('P4', 'P5', 'P6', 'P7', 'P8')
            ),
            member_current_level_snapshot TEXT CHECK (
                member_current_level_snapshot IS NULL
                OR member_current_level_snapshot IN ('P4', 'P5', 'P6', 'P7', 'P8')
            ),
            member_target_level_snapshot TEXT CHECK (
                member_target_level_snapshot IS NULL
                OR member_target_level_snapshot IN ('P4', 'P5', 'P6', 'P7', 'P8')
            ),
            capability_standard_version_id BIGINT NOT NULL,
            planning_snapshot_id BIGINT NOT NULL,
            assessment_revision BIGINT NOT NULL,
            planning_source_type TEXT NOT NULL DEFAULT 'assessment_approval'
                CHECK (planning_source_type IN ('assessment_approval')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE (source_assessment_detail_id),
            CONSTRAINT proposal_detail_snapshot_version_node_fk
                FOREIGN KEY (planning_snapshot_id, capability_standard_version_id, l3_node_id)
                REFERENCES capability_standard_planning_snapshot (
                    id, capability_standard_version_id, l3_node_id
                ),
            CONSTRAINT proposal_detail_source_assessment_node_fk
                FOREIGN KEY (source_assessment_detail_id, assessment_id, l3_node_id)
                REFERENCES assessment_detail (id, assessment_id, l3_node_id),
            CHECK (
                plan_quarter IS NULL OR plan_month IS NULL
                OR (plan_quarter = 'Q1' AND plan_month BETWEEN 1 AND 3)
                OR (plan_quarter = 'Q2' AND plan_month BETWEEN 4 AND 6)
                OR (plan_quarter = 'Q3' AND plan_month BETWEEN 7 AND 9)
                OR (plan_quarter = 'Q4' AND plan_month BETWEEN 10 AND 12)
            )
        )
        """
    )
    # P1-4: idempotent guards for databases where the detail table already
    # exists without the NOT NULL / composite FKs.
    connection.execute(
        """
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'annual_plan_change_proposal_detail'
                  AND column_name = 'planning_snapshot_id'
                  AND is_nullable = 'YES'
            ) THEN
                ALTER TABLE annual_plan_change_proposal_detail
                ALTER COLUMN planning_snapshot_id SET NOT NULL;
            END IF;
        END $$
        """
    )
    # P1-2 (2nd review): every assessment_approval proposal detail is a frozen
    # slice of the approved plan selection — scope, member level snapshots,
    # current/effective target, gap, priority, timing and the effective-target
    # consistency rule are all required at the DB level.
    _add_check(
        connection,
        "annual_plan_change_proposal_detail",
        "proposal_detail_approval_completeness",
        "include_in_plan IS TRUE"
        " AND member_priority IS NOT NULL"
        " AND member_priority IN ('高', '中', '低')"
        " AND scope_type IS NOT NULL"
        " AND current_level IS NOT NULL"
        " AND effective_target_level IS NOT NULL"
        " AND gap_value IS NOT NULL"
        " AND plan_quarter IS NOT NULL AND plan_month IS NOT NULL"
        " AND standard_job_level_snapshot IS NOT NULL"
        " AND member_current_level_snapshot IS NOT NULL"
        " AND member_target_level_snapshot IS NOT NULL"
        " AND standard_target_level IS NOT NULL"
        " AND assessment_revision IS NOT NULL"
        " AND capability_standard_version_id IS NOT NULL"
        " AND planning_snapshot_id IS NOT NULL"
        " AND l1_code IS NOT NULL AND l1_name IS NOT NULL"
        " AND l2_code IS NOT NULL AND l2_name IS NOT NULL"
        " AND l3_code IS NOT NULL AND l3_name IS NOT NULL"
        " AND ("
        "   (adjusted_target_level IS NOT NULL"
        "    AND effective_target_level = adjusted_target_level)"
        "   OR"
        "   (adjusted_target_level IS NULL"
        "    AND effective_target_level = standard_target_level)"
        " )",
    )
    _add_fk(
        connection,
        "annual_plan_change_proposal_detail",
        "proposal_detail_snapshot_version_node_fk",
        "FOREIGN KEY (planning_snapshot_id, capability_standard_version_id, l3_node_id) "
        "REFERENCES capability_standard_planning_snapshot ("
        "id, capability_standard_version_id, l3_node_id)",
    )
    _add_fk(
        connection,
        "annual_plan_change_proposal_detail",
        "proposal_detail_source_assessment_node_fk",
        "FOREIGN KEY (source_assessment_detail_id, assessment_id, l3_node_id) "
        "REFERENCES assessment_detail (id, assessment_id, l3_node_id)",
    )
    # P1-B (3rd review): the detail's assessment must equal its parent
    # proposal's source assessment — a detail can never hang under a proposal
    # created from a different assessment.  The unique key on the parent
    # exists inline on fresh databases and is created explicitly here for
    # upgraded ones.
    connection.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uniq_proposal_id_source
        ON annual_plan_change_proposal (id, source_assessment_id)
        """
    )
    _add_fk(
        connection,
        "annual_plan_change_proposal_detail",
        "proposal_detail_parent_source_fk",
        "FOREIGN KEY (proposal_id, assessment_id) "
        "REFERENCES annual_plan_change_proposal (id, source_assessment_id)",
    )


def _create_review_idempotency_table(connection: psycopg.Connection) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS review_idempotency_key (
            buddy_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE,
            idempotency_key TEXT NOT NULL,
            assessment_id BIGINT NOT NULL REFERENCES assessment(id) ON DELETE CASCADE,
            review_id BIGINT NOT NULL REFERENCES assessment_review(id) ON DELETE CASCADE,
            fingerprint TEXT NOT NULL,
            response JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            PRIMARY KEY (buddy_id, idempotency_key)
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_review_idem_assessment
        ON review_idempotency_key(assessment_id)
        """
    )


def _enable_planning_provenance_immutability(connection: psycopg.Connection) -> None:
    """P1-A (3rd review): once a plan or plan item carries assessment_approval
    provenance, the discriminator and the source identity are immutable —
    they can never be downgraded to the legacy NULL branch (even together)
    and the source can never drift, including between two assessments of the
    same member/year."""
    connection.execute(
        """
        CREATE OR REPLACE FUNCTION guard_planning_provenance_immutable()
        RETURNS TRIGGER AS $$
        BEGIN
            IF TG_OP = 'UPDATE' THEN
                IF OLD.planning_source_type IS NOT NULL
                   AND NEW.planning_source_type IS DISTINCT FROM OLD.planning_source_type THEN
                    RAISE EXCEPTION
                        'planning provenance discriminator is immutable'
                        USING ERRCODE = 'P0001';
                END IF;
                IF OLD.source_assessment_id IS NOT NULL
                   AND NEW.source_assessment_id IS DISTINCT FROM OLD.source_assessment_id THEN
                    RAISE EXCEPTION
                        'planning source identity is immutable'
                        USING ERRCODE = 'P0001';
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    for table in ("annual_growth_plan", "plan_item"):
        connection.execute(
            f"DROP TRIGGER IF EXISTS trg_planning_provenance_immutable ON {table}"
        )
        connection.execute(
            f"""
            CREATE TRIGGER trg_planning_provenance_immutable
            BEFORE UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION guard_planning_provenance_immutable()
            """
        )


def _guard_proposal_source_against_plan_first_source(
    connection: psycopg.Connection,
) -> None:
    """4th review: the change proposal can never reuse the assessment that
    generated its target plan (the first approval source).  The formal plan
    is generated by the first approval; only subsequent assessments of the
    same member/year may generate adjustment proposals.  Both directions are
    guarded so the pair can never drift into an illegal state:

    - ``proposal.source_assessment_id`` must not equal the target plan's
      ``source_assessment_id`` (INSERT and UPDATE),
    - the plan's ``source_assessment_id`` (legacy NULL → non-NULL backfill)
      must not equal an existing proposal's source for the same plan.

    Both directions serialise on the target plan ROW itself (READ COMMITTED):
    the proposal guard reads the plan source under ``SELECT ... FOR UPDATE``
    and the plan-side UPDATE already holds the row lock, so the pair can
    never race into equal sources — the check always observes the latest
    committed value after any wait.  Existing rows are never scanned or
    rewritten — the guard only governs new writes.
    """
    connection.execute(
        """
        CREATE OR REPLACE FUNCTION guard_proposal_source_not_plan_first_source()
        RETURNS TRIGGER AS $$
        DECLARE
            plan_source BIGINT;
        BEGIN
            -- 5th review: serialise on the target plan ROW itself.  Both
            -- directions (proposal INSERT/UPDATE and the plan's legacy
            -- source backfill) contend for the same single row lock, so the
            -- read below always observes the latest committed plan source.
            -- A row lock (not an advisory key) is used on purpose: an
            -- advisory lock held here would deadlock against the INSERT's
            -- own foreign-key row lock when the plan-side UPDATE holds the
            -- row first (proposal waits on the row, backfill waits on the
            -- advisory key).
            SELECT source_assessment_id INTO plan_source
            FROM annual_growth_plan
            WHERE id = NEW.target_annual_growth_plan_id
            FOR UPDATE;
            IF plan_source IS NOT NULL
               AND NEW.source_assessment_id = plan_source THEN
                RAISE EXCEPTION
                    'change proposal source cannot be the target plan''s first source assessment'
                    USING ERRCODE = 'P0001';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    connection.execute(
        "DROP TRIGGER IF EXISTS trg_proposal_source_not_plan_first_source "
        "ON annual_plan_change_proposal"
    )
    connection.execute(
        """
        CREATE TRIGGER trg_proposal_source_not_plan_first_source
        BEFORE INSERT OR UPDATE ON annual_plan_change_proposal
        FOR EACH ROW EXECUTE FUNCTION guard_proposal_source_not_plan_first_source()
        """
    )
    connection.execute(
        """
        CREATE OR REPLACE FUNCTION guard_plan_source_not_proposal_source()
        RETURNS TRIGGER AS $$
        BEGIN
            IF TG_OP = 'UPDATE' AND NEW.source_assessment_id IS NOT NULL THEN
                -- The UPDATE already holds the plan row lock; the proposal
                -- guard takes the same row lock (SELECT ... FOR UPDATE)
                -- before reading this column, so the EXISTS below sees every
                -- committed proposal for this plan.  Single lock object, no
                -- ordering differences, no deadlock.
                IF EXISTS (
                    SELECT 1 FROM annual_plan_change_proposal p
                    WHERE p.target_annual_growth_plan_id = NEW.id
                      AND p.source_assessment_id = NEW.source_assessment_id
                ) THEN
                    RAISE EXCEPTION
                        'plan first source cannot be an existing proposal source of the same plan'
                        USING ERRCODE = 'P0001';
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    connection.execute(
        "DROP TRIGGER IF EXISTS trg_plan_source_not_proposal_source "
        "ON annual_growth_plan"
    )
    connection.execute(
        """
        CREATE TRIGGER trg_plan_source_not_proposal_source
        BEFORE UPDATE ON annual_growth_plan
        FOR EACH ROW EXECUTE FUNCTION guard_plan_source_not_proposal_source()
        """
    )


def upgrade(connection: psycopg.Connection) -> None:
    # Order matters: the legacy backfill inserts snapshots for
    # already-published/archived versions, so the immutability trigger may only
    # be enabled *after* the backfill completes.
    _create_planning_snapshot(connection)
    _capture_legacy_planning_snapshots(connection)
    _enable_planning_snapshot_immutability(connection)
    _extend_annual_growth_plan(connection)
    _extend_plan_item(connection)
    _extend_assessment_review(connection)
    _extend_buddy_relationship(connection)
    _create_change_proposal_tables(connection)
    _create_review_idempotency_table(connection)
    _enable_planning_provenance_immutability(connection)
    _guard_proposal_source_against_plan_first_source(connection)
