"""v0010: Learning execution — Task state machine, append-only logs, Evidence
version chains and immutable Evidence Review.

Additive, forward-only. Adds:

- ``learning_task`` execution columns: revision, actual_started_at,
  actual_completed_at, delay_reason, pause_reason, cancel_reason,
  revised_due_date; the status dictionary tightens to the six final states
  (legacy ``待 Evidence Review`` rows backfilled to ``进行中``);
  ``completion_quality`` gains the final dictionary CHECK — legacy free-text
  values are nulled (no production rows exist for that never-shipped field);
- ``task_transition_history`` — append-only audit of every task transition
  (from_status, to_status, reason, actor, occurred_at, request idempotency);
- ``learning_progress_log`` append-only semantics: created_at,
  invalidated_at/invalidated_by, correction_of_log_id, idempotency_key
  (partial unique); hours CHECK tightens to ``> 0`` (legacy 0-hour rows are
  backfilled to 1 with a visible note marker);
- ``evidence``: submitted_by, description, evidence_type, url, file_reference,
  file_name, mime_type, file_size, supersedes_evidence_id, revision;
- ``evidence_review``: idempotency_key (partial unique) — one immutable
  review row per evidence version stays enforced by the existing
  ``UNIQUE(evidence_id)``;
- ``plan_item``: plan_start_date/plan_end_date order CHECK, legacy plan dates
  backfilled from target_month (missing dates only).

No columns, tables or rows are removed; historical data stays readable.
"""

import psycopg

# ruff: noqa: E501

_FINAL_TASK_STATUSES = (
    "未开始",
    "进行中",
    "已完成",
    "延期",
    "暂停",
    "取消",
)

_COMPLETION_QUALITY_VALUES = ("达到预期", "部分达到", "超出预期")


def _add_column(
    connection: psycopg.Connection,
    table: str,
    column: str,
    definition: str,
) -> None:
    connection.execute(
        f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {column} {definition}"
    )


def _drop_constraint(
    connection: psycopg.Connection, table: str, constraint: str
) -> None:
    connection.execute(
        f"""
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = '{table}'::regclass AND conname = '{constraint}'
            ) THEN
                ALTER TABLE {table} DROP CONSTRAINT {constraint};
            END IF;
        END $$
        """
    )


def _add_check(
    connection: psycopg.Connection,
    table: str,
    constraint: str,
    expression: str,
) -> None:
    connection.execute(
        f"""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = '{table}'::regclass AND conname = '{constraint}'
            ) THEN
                ALTER TABLE {table} ADD CONSTRAINT {constraint} CHECK ({expression});
            END IF;
        END $$
        """
    )


def _create_transition_history(connection: psycopg.Connection) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS task_transition_history (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            learning_task_id BIGINT NOT NULL
                REFERENCES learning_task(id) ON DELETE CASCADE,
            from_status TEXT NOT NULL,
            to_status TEXT NOT NULL,
            reason TEXT,
            actor_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE,
            occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            request_key TEXT,
            fingerprint TEXT,
            UNIQUE (learning_task_id, request_key)
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_task_transition_history_task_id
        ON task_transition_history(learning_task_id)
        """
    )


def _extend_learning_task(connection: psycopg.Connection) -> None:
    for column, definition in (
        ("revision", "INT NOT NULL DEFAULT 0"),
        ("actual_started_at", "TIMESTAMPTZ"),
        ("actual_completed_at", "TIMESTAMPTZ"),
        ("delay_reason", "TEXT"),
        ("pause_reason", "TEXT"),
        ("cancel_reason", "TEXT"),
        ("revised_due_date", "DATE"),
    ):
        _add_column(connection, "learning_task", column, definition)

    # Tighten the status dictionary to the six final states.
    _drop_constraint(connection, "learning_task", "learning_task_status_check")
    connection.execute(
        "UPDATE learning_task SET status = '进行中' WHERE status = '待 Evidence Review'"
    )
    allowed = ", ".join(f"'{s}'" for s in _FINAL_TASK_STATUSES)
    _add_check(
        connection,
        "learning_task",
        "learning_task_status_check",
        f"status IN ({allowed})",
    )

    # Final completion_quality dictionary.  Legacy free-text values (the field
    # was never validated and has no shipped writes) are nulled so the CHECK
    # can be enforced going forward.
    connection.execute(
        """
        UPDATE learning_task
        SET completion_quality = NULL
        WHERE completion_quality IS NOT NULL
          AND completion_quality NOT IN ('达到预期', '部分达到', '超出预期')
        """
    )
    _add_check(
        connection,
        "learning_task",
        "learning_task_completion_quality_check",
        "completion_quality IS NULL"
        " OR completion_quality IN ('达到预期', '部分达到', '超出预期')",
    )


def _extend_progress_log(connection: psycopg.Connection) -> None:
    for column, definition in (
        ("created_at", "TIMESTAMPTZ NOT NULL DEFAULT NOW()"),
        ("invalidated_at", "TIMESTAMPTZ"),
        ("invalidated_by", "BIGINT REFERENCES tcp_user(id)"),
        (
            "correction_of_log_id",
            "BIGINT REFERENCES learning_progress_log(id)",
        ),
        ("idempotency_key", "TEXT"),
    ):
        _add_column(connection, "learning_progress_log", column, definition)

    connection.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uniq_progress_log_idempotency_key
        ON learning_progress_log(idempotency_key)
        WHERE idempotency_key IS NOT NULL
        """
    )

    # Tighten hours to > 0; legacy 0-hour rows become 1 with a visible marker.
    _drop_constraint(
        connection,
        "learning_progress_log",
        "learning_progress_log_actual_hours_check",
    )
    connection.execute(
        """
        UPDATE learning_progress_log
        SET actual_hours = 1,
            note = COALESCE(note || ' ', '')
                  || '(v0010: legacy 0-hour entry backfilled to 1)'
        WHERE actual_hours = 0
        """
    )
    _add_check(
        connection,
        "learning_progress_log",
        "learning_progress_log_actual_hours_check",
        "actual_hours > 0",
    )


def _extend_evidence(connection: psycopg.Connection) -> None:
    for column, definition in (
        ("submitted_by", "BIGINT REFERENCES tcp_user(id)"),
        ("description", "TEXT"),
        (
            "evidence_type",
            "TEXT CHECK (evidence_type IS NULL"
            " OR evidence_type IN ('link', 'file'))",
        ),
        ("url", "TEXT"),
        ("file_reference", "TEXT"),
        ("file_name", "TEXT"),
        ("mime_type", "TEXT"),
        ("file_size", "BIGINT"),
        ("supersedes_evidence_id", "BIGINT REFERENCES evidence(id)"),
        ("revision", "INT NOT NULL DEFAULT 0"),
    ):
        _add_column(connection, "evidence", column, definition)

    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_evidence_supersedes
        ON evidence(supersedes_evidence_id)
        """
    )


def _extend_evidence_review(connection: psycopg.Connection) -> None:
    _add_column(
        connection, "evidence_review", "idempotency_key", "TEXT"
    )
    connection.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uniq_evidence_review_idempotency_key
        ON evidence_review(idempotency_key)
        WHERE idempotency_key IS NOT NULL
        """
    )


def _extend_plan_item(connection: psycopg.Connection) -> None:
    _add_column(connection, "plan_item", "revision", "INT NOT NULL DEFAULT 0")


def _backfill_plan_item_dates(connection: psycopg.Connection) -> None:
    # Pre-#63 items carry target_month only; #62 items carry plan_month.
    # Fill missing plan dates from the plan month (first/last day), sourced
    # from plan_month first, legacy target_month second.
    connection.execute(
        """
        UPDATE plan_item pi
        SET plan_start_date = COALESCE(
                pi.plan_start_date,
                MAKE_DATE(agp.year, COALESCE(pi.plan_month, pi.target_month), 1)
            ),
            plan_end_date = COALESCE(
                pi.plan_end_date,
                (MAKE_DATE(
                     agp.year, COALESCE(pi.plan_month, pi.target_month) + 1, 1
                 ) - INTERVAL '1 day')::date
            )
        FROM annual_growth_plan agp
        WHERE agp.id = pi.annual_growth_plan_id
          AND (pi.plan_start_date IS NULL OR pi.plan_end_date IS NULL)
          AND COALESCE(pi.plan_month, pi.target_month) BETWEEN 1 AND 12
        """
    )
    _add_check(
        connection,
        "plan_item",
        "plan_item_plan_dates_order_check",
        "plan_start_date IS NULL"
        " OR plan_end_date IS NULL"
        " OR plan_start_date <= plan_end_date",
    )


def upgrade(connection: psycopg.Connection) -> None:
    _create_transition_history(connection)
    _extend_learning_task(connection)
    _extend_progress_log(connection)
    _extend_evidence(connection)
    _extend_evidence_review(connection)
    _extend_plan_item(connection)
    _backfill_plan_item_dates(connection)
