"""v0011: Monthly Review — Member-written month retrospectives.

Additive, forward-only. Adds:

- ``monthly_review`` — one row per (member, year, month) holding the
  Member-written fields (main_output, problems, next_month_focus, notes) with
  a CAS ``revision`` counter and a unique key on (member_id, year, month);
- ``monthly_review_history`` — append-only version table; every revision of
  every review is preserved immutably (one row per revision, never updated
  or deleted by the application).

Reads aggregate over the existing six-state ``plan_item`` rows and the
append-only ``learning_progress_log`` rows (valid logs only), so no data
migration is needed. No columns, tables or rows are removed; historical data
stays readable.
"""

import psycopg


def upgrade(connection: psycopg.Connection) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS monthly_review (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            member_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE,
            year INT NOT NULL,
            month INT NOT NULL CHECK (month BETWEEN 1 AND 12),
            revision INT NOT NULL DEFAULT 0,
            main_output TEXT,
            problems TEXT,
            next_month_focus TEXT,
            notes TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE (member_id, year, month)
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS monthly_review_history (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            monthly_review_id BIGINT NOT NULL
                REFERENCES monthly_review(id) ON DELETE CASCADE,
            revision INT NOT NULL CHECK (revision > 0),
            main_output TEXT,
            problems TEXT,
            next_month_focus TEXT,
            notes TEXT,
            changed_by BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE,
            changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE (monthly_review_id, revision)
        )
        """
    )
