"""v0017: preserve a task's selected immutable requirement snapshot."""

import psycopg


def upgrade(connection: psycopg.Connection) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS task_requirement_decision (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            learning_task_id BIGINT NOT NULL
                REFERENCES learning_task(id) ON DELETE CASCADE,
            proposal_detail_id BIGINT NOT NULL
                REFERENCES annual_plan_change_proposal_detail(id) ON DELETE RESTRICT,
            selected_snapshot_id BIGINT NOT NULL
                REFERENCES capability_standard_planning_snapshot(id) ON DELETE RESTRICT,
            choice TEXT NOT NULL CHECK (choice IN ('adopt_new', 'continue_current')),
            revision INT NOT NULL DEFAULT 0,
            decided_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE (learning_task_id, proposal_detail_id)
        )
        """
    )
