import psycopg


def create_assessment_schema(connection: psycopg.Connection) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS assessment (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            member_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE,
            year INT NOT NULL,
            version INT NOT NULL DEFAULT 1,
            assessment_type TEXT NOT NULL
                CHECK (assessment_type IN ('年度', '年中更新', '晋升复核')),
            status TEXT NOT NULL
                CHECK (status IN ('草稿', '待复核', '已复核', '建议调整', '已归档')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            submitted_at TIMESTAMPTZ,
            archived_at TIMESTAMPTZ,
            UNIQUE(member_id, year, version)
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS assessment_detail (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            assessment_id BIGINT NOT NULL REFERENCES assessment(id) ON DELETE CASCADE,
            l3_code TEXT NOT NULL,
            current_level INT CHECK (
                current_level IS NULL OR current_level BETWEEN 1 AND 5
            ),
            target_level INT CHECK (
                target_level IS NULL OR target_level BETWEEN 1 AND 5
            ),
            standard_target_applicable BOOLEAN,
            standard_target_level INT CHECK (
                standard_target_level IS NULL
                OR standard_target_level BETWEEN 1 AND 5
            ),
            target_adjusted BOOLEAN NOT NULL DEFAULT FALSE,
            adjusted_target_level INT CHECK (
                adjusted_target_level IS NULL
                OR adjusted_target_level BETWEEN 1 AND 5
            ),
            target_adjustment_reason TEXT,
            target_snapshot_source TEXT,
            target_compatibility_error TEXT,
            gap_value INT,
            evidence_note TEXT,
            plan_candidate BOOLEAN NOT NULL DEFAULT FALSE,
            CHECK (
                standard_target_applicable IS DISTINCT FROM FALSE
                OR standard_target_level IS NULL
            ),
            CHECK (
                (target_adjusted = FALSE
                 AND adjusted_target_level IS NULL
                 AND target_adjustment_reason IS NULL)
                OR
                (target_adjusted = TRUE
                 AND standard_target_applicable = TRUE
                 AND adjusted_target_level BETWEEN 1 AND 5
                 AND BTRIM(target_adjustment_reason) <> '')
            ),
            UNIQUE(assessment_id, l3_code)
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS gap (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            assessment_id BIGINT NOT NULL REFERENCES assessment(id) ON DELETE CASCADE,
            l3_code TEXT NOT NULL,
            current_level INT NOT NULL,
            target_level INT NOT NULL,
            gap_value INT NOT NULL,
            priority TEXT NOT NULL DEFAULT '中'
                CHECK (priority IN ('高', '中', '低')),
            plan_candidate BOOLEAN NOT NULL DEFAULT FALSE,
            UNIQUE(assessment_id, l3_code)
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS assessment_review (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            assessment_id BIGINT NOT NULL REFERENCES assessment(id) ON DELETE CASCADE,
            sequence INT NOT NULL,
            buddy_id BIGINT REFERENCES tcp_user(id) ON DELETE SET NULL,
            conclusion TEXT CHECK (conclusion IN ('认可', '建议调整')),
            feedback TEXT,
            reviewed_at TIMESTAMPTZ,
            status TEXT NOT NULL CHECK (status IN ('待复核', '已闭环')),
            UNIQUE(assessment_id, sequence)
        )
        """
    )
