import psycopg


def create_assessment_schema(connection: psycopg.Connection) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS assessment (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            member_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE,
            year INT NOT NULL,
            version INT NOT NULL DEFAULT 1,
            assessment_type TEXT NOT NULL
                CHECK (assessment_type IN ('年度', '年中更新', '晋升复核')),
            status TEXT NOT NULL
                CHECK (status IN ('草稿', '待复核', '已复核', '建议调整', '已归档')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            submitted_at TIMESTAMPTZ,
            archived_at TIMESTAMPTZ,
            revision BIGINT NOT NULL DEFAULT 1,
            member_current_level_snapshot TEXT CHECK (
                member_current_level_snapshot IS NULL
                OR member_current_level_snapshot IN ('P4', 'P5', 'P6', 'P7', 'P8')
            ),
            member_target_level_snapshot TEXT CHECK (
                member_target_level_snapshot IS NULL
                OR member_target_level_snapshot IN ('P4', 'P5', 'P6', 'P7', 'P8')
            ),
            capability_standard_version_id BIGINT,
            assessment_scope_version TEXT,
            UNIQUE(member_id, year, version)
        )
        """
    )
    connection.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS assessment_one_open_per_scope
        ON assessment (member_id, year, assessment_type)
        WHERE status IN ('草稿', '建议调整')
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS assessment_detail (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            assessment_id BIGINT NOT NULL REFERENCES assessment(id) ON DELETE CASCADE,
            l3_code TEXT NOT NULL,
            current_level INT CHECK (
                current_level IS NULL OR current_level BETWEEN 1 AND 5
            ),
            current_level_explicitly_cleared BOOLEAN NOT NULL DEFAULT FALSE,
            target_level INT CHECK (
                target_level IS NULL OR target_level BETWEEN 1 AND 5
            ),
            standard_target_applicable BOOLEAN,
            standard_target_level INT CHECK (
                standard_target_level IS NULL
                OR standard_target_level BETWEEN 1 AND 5
            ),
            target_adjusted BOOLEAN NOT NULL DEFAULT FALSE,
            adjusted_target_level INT CHECK (
                adjusted_target_level IS NULL
                OR adjusted_target_level BETWEEN 1 AND 5
            ),
            target_adjustment_reason TEXT,
            target_snapshot_source TEXT,
            target_compatibility_error TEXT,
            gap_value INT,
            evidence_note TEXT,
            plan_candidate BOOLEAN NOT NULL DEFAULT FALSE,
            inherited_from_assessment_id BIGINT
                REFERENCES assessment(id) ON DELETE SET NULL,
            inherited_current_level INT CHECK (
                inherited_current_level IS NULL
                OR inherited_current_level BETWEEN 1 AND 5
            ),
            inherited_evidence_note TEXT,
            l3_node_id BIGINT,
            scope_type TEXT CHECK (
                scope_type IS NULL
                OR scope_type IN ('current_required', 'target_progressive')
            ),
            standard_job_level_snapshot TEXT CHECK (
                standard_job_level_snapshot IS NULL
                OR standard_job_level_snapshot IN ('P4', 'P5', 'P6', 'P7', 'P8')
            ),
            l1_code TEXT,
            l1_name TEXT,
            l2_code TEXT,
            l2_name TEXT,
            l3_name TEXT,
            CHECK (
                standard_target_applicable IS DISTINCT FROM FALSE
                OR standard_target_level IS NULL
            ),
            CHECK (
                (target_adjusted = FALSE
                 AND adjusted_target_level IS NULL
                 AND target_adjustment_reason IS NULL)
                OR
                (target_adjusted = TRUE
                 AND standard_target_applicable = TRUE
                 AND adjusted_target_level BETWEEN 1 AND 5
                 AND BTRIM(target_adjustment_reason) <> '')
            ),
            UNIQUE(assessment_id, l3_code)
        )
        """
    )
    connection.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS assessment_detail_node_identity
        ON assessment_detail (assessment_id, l3_node_id)
        WHERE l3_node_id IS NOT NULL
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS assessment_idempotency_key (
            member_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE,
            idempotency_key TEXT NOT NULL,
            request_fingerprint TEXT NOT NULL,
            assessment_id BIGINT NOT NULL REFERENCES assessment(id) ON DELETE CASCADE,
            response JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            PRIMARY KEY (member_id, idempotency_key)
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS gap (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            assessment_id BIGINT NOT NULL REFERENCES assessment(id) ON DELETE CASCADE,
            l3_code TEXT NOT NULL,
            current_level INT NOT NULL,
            target_level INT NOT NULL,
            gap_value INT NOT NULL,
            priority TEXT NOT NULL DEFAULT '中'
                CHECK (priority IN ('高', '中', '低')),
            plan_candidate BOOLEAN NOT NULL DEFAULT FALSE,
            UNIQUE(assessment_id, l3_code)
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS assessment_review (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            assessment_id BIGINT NOT NULL REFERENCES assessment(id) ON DELETE CASCADE,
            sequence INT NOT NULL,
            buddy_id BIGINT REFERENCES tcp_user(id) ON DELETE SET NULL,
            conclusion TEXT CHECK (conclusion IN ('认可', '建议调整')),
            feedback TEXT,
            reviewed_at TIMESTAMPTZ,
            status TEXT NOT NULL CHECK (status IN ('待复核', '已闭环')),
            UNIQUE(assessment_id, sequence)
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS assessment_draft_target_repair_audit (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            assessment_id BIGINT NOT NULL REFERENCES assessment(id) ON DELETE RESTRICT,
            actor_user_id BIGINT NOT NULL,
            old_revision BIGINT NOT NULL,
            new_revision BIGINT NOT NULL,
            old_current_level_source TEXT,
            new_current_level_source TEXT NOT NULL,
            old_target_level_source TEXT,
            new_target_level_source TEXT NOT NULL,
            old_standard_version_id BIGINT,
            new_standard_version_id BIGINT NOT NULL,
            result TEXT NOT NULL CHECK (result = 'repaired'),
            summary JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_assessment_draft_target_repair_audit_assessment
        ON assessment_draft_target_repair_audit(assessment_id, created_at DESC)
        """
    )
