import psycopg


def create_planning_schema(connection: psycopg.Connection) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS annual_growth_plan (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            member_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE,
            year INT NOT NULL,
            plan_cycle INT NOT NULL DEFAULT 12,
            status TEXT NOT NULL DEFAULT '制定中'
                CHECK (status IN ('制定中', '执行中', '已归档')),
            start_date DATE,
            end_date DATE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE(member_id, year)
        )
        """
    )
    connection.execute(
        """
        CREATE OR REPLACE FUNCTION set_annual_growth_plan_default_dates()
        RETURNS TRIGGER AS $$
        BEGIN
            IF NEW.start_date IS NULL THEN
                NEW.start_date := MAKE_DATE(NEW.year, 1, 1);
            END IF;
            IF NEW.end_date IS NULL THEN
                NEW.end_date := MAKE_DATE(NEW.year, 12, 31);
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    connection.execute(
        """
        DROP TRIGGER IF EXISTS trg_annual_growth_plan_default_dates
        ON annual_growth_plan
        """
    )
    connection.execute(
        """
        CREATE TRIGGER trg_annual_growth_plan_default_dates
        BEFORE INSERT ON annual_growth_plan
        FOR EACH ROW
        EXECUTE FUNCTION set_annual_growth_plan_default_dates()
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS growth_goal (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            gap_id BIGINT NOT NULL REFERENCES gap(id) ON DELETE CASCADE,
            annual_growth_plan_id BIGINT NOT NULL
                REFERENCES annual_growth_plan(id) ON DELETE CASCADE,
            l3_code TEXT NOT NULL,
            year INT NOT NULL,
            target_level INT NOT NULL,
            priority TEXT NOT NULL DEFAULT '中'
                CHECK (priority IN ('高', '中', '低')),
            UNIQUE(annual_growth_plan_id, l3_code)
        )
        """
    )
