import psycopg


def create_planning_schema(connection: psycopg.Connection) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS annual_growth_plan (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            member_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE,
            year INT NOT NULL,
            plan_cycle INT NOT NULL DEFAULT 12,
            status TEXT NOT NULL DEFAULT '制定中'
                CHECK (status IN ('制定中', '执行中', '已归档')),
            start_date DATE,
            end_date DATE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE(member_id, year)
        )
        """
    )
    connection.execute(
        """
        CREATE OR REPLACE FUNCTION set_annual_growth_plan_default_dates()
        RETURNS TRIGGER AS $$
        BEGIN
            IF NEW.start_date IS NULL THEN
                NEW.start_date := MAKE_DATE(NEW.year, 1, 1);
            END IF;
            IF NEW.end_date IS NULL THEN
                NEW.end_date := MAKE_DATE(NEW.year, 12, 31);
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    connection.execute(
        """
        DROP TRIGGER IF EXISTS trg_annual_growth_plan_default_dates
        ON annual_growth_plan
        """
    )
    connection.execute(
        """
        CREATE TRIGGER trg_annual_growth_plan_default_dates
        BEFORE INSERT ON annual_growth_plan
        FOR EACH ROW
        EXECUTE FUNCTION set_annual_growth_plan_default_dates()
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS growth_goal (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            gap_id BIGINT NOT NULL REFERENCES gap(id) ON DELETE CASCADE,
            annual_growth_plan_id BIGINT NOT NULL
                REFERENCES annual_growth_plan(id) ON DELETE CASCADE,
            l3_code TEXT NOT NULL,
            year INT NOT NULL,
            target_level INT NOT NULL,
            priority TEXT NOT NULL DEFAULT '中'
                CHECK (priority IN ('高', '中', '低')),
            UNIQUE(annual_growth_plan_id, l3_code)
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS plan_item (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            annual_growth_plan_id BIGINT NOT NULL
                REFERENCES annual_growth_plan(id) ON DELETE CASCADE,
            growth_goal_id BIGINT NOT NULL REFERENCES growth_goal(id) ON DELETE CASCADE,
            l3_code TEXT NOT NULL,
            current_level INT NOT NULL,
            target_level INT NOT NULL,
            priority TEXT NOT NULL DEFAULT '中'
                CHECK (priority IN ('高', '中', '低')),
            learning_material TEXT,
            learning_task_content TEXT,
            expected_output TEXT,
            estimated_hours TEXT,
            plan_start_date DATE,
            plan_end_date DATE,
            target_month INT,
            status TEXT NOT NULL DEFAULT '未开始'
                CHECK (status IN (
                    '未开始', '进行中', '已完成', '延期', '暂停', '取消'
                )),
            UNIQUE(annual_growth_plan_id, l3_code),
            UNIQUE(growth_goal_id)
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS learning_task (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            plan_item_id BIGINT NOT NULL REFERENCES plan_item(id) ON DELETE CASCADE,
            l3_code TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT '未开始'
                CHECK (status IN (
                    '未开始', '进行中', '待 Evidence Review',
                    '已完成', '延期', '暂停', '取消'
                )),
            actual_start_date DATE,
            actual_end_date DATE,
            actual_hours INT DEFAULT 0,
            completion_quality TEXT,
            review_conclusion TEXT,
            next_action TEXT,
            UNIQUE(plan_item_id)
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS learning_progress_log (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            task_id BIGINT NOT NULL REFERENCES learning_task(id) ON DELETE CASCADE,
            record_date DATE NOT NULL,
            actual_hours INT NOT NULL CHECK (actual_hours >= 0),
            note TEXT,
            recorder_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_learning_progress_log_task_id
        ON learning_progress_log(task_id)
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_learning_progress_log_recorder_id
        ON learning_progress_log(recorder_id)
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS evidence (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            learning_task_id BIGINT NOT NULL
                REFERENCES learning_task(id) ON DELETE CASCADE,
            l3_code TEXT NOT NULL,
            version_number INT NOT NULL CHECK (version_number > 0),
            content TEXT,
            evidence_link TEXT,
            status TEXT NOT NULL DEFAULT '草稿'
                CHECK (status IN (
                    '草稿', '待 Review', '通过', '需补充', '驳回', '已归档'
                )),
            submitted_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE(learning_task_id, version_number)
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_evidence_learning_task_id
        ON evidence(learning_task_id)
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS evidence_review (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            evidence_id BIGINT NOT NULL UNIQUE
                REFERENCES evidence(id) ON DELETE CASCADE,
            buddy_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE,
            status TEXT NOT NULL DEFAULT '待 Review'
                CHECK (status IN ('待 Review', '通过', '需补充', '驳回', '已闭环')),
            conclusion TEXT CHECK (conclusion IN ('通过', '需补充', '驳回')),
            feedback TEXT,
            reviewed_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_evidence_review_evidence_id
        ON evidence_review(evidence_id)
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_evidence_review_buddy_id
        ON evidence_review(buddy_id)
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS capability_profile (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            member_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE,
            year INT NOT NULL,
            status TEXT NOT NULL DEFAULT '已生成'
                CHECK (status IN ('生成中', '已生成')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE(member_id, year)
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS team_annual_capability_plan (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code TEXT NOT NULL UNIQUE,
            year INT NOT NULL UNIQUE,
            publisher_id BIGINT NOT NULL,
            resource_arrangement TEXT,
            description TEXT,
            published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            status TEXT NOT NULL DEFAULT '已发布'
                CHECK (status IN ('已发布', '已归档')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS team_annual_capability_plan_domain (
            plan_id BIGINT NOT NULL
                REFERENCES team_annual_capability_plan(id) ON DELETE CASCADE,
            l1_code TEXT NOT NULL,
            PRIMARY KEY (plan_id, l1_code)
        )
        """
    )
