import psycopg


def create_planning_schema(connection: psycopg.Connection) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS annual_growth_plan (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            member_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE,
            year INT NOT NULL,
            plan_cycle INT NOT NULL DEFAULT 12,
            status TEXT NOT NULL DEFAULT '制定中'
                CHECK (status IN ('制定中', '执行中', '已归档')),
            start_date DATE,
            end_date DATE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            source_assessment_id BIGINT REFERENCES assessment(id) ON DELETE RESTRICT,
            planning_source_type TEXT
                CHECK (planning_source_type IS NULL
                       OR planning_source_type IN ('assessment_approval')),
            UNIQUE(member_id, year)
        )
        """
    )
    connection.execute(
        """
        CREATE OR REPLACE FUNCTION set_annual_growth_plan_default_dates()
        RETURNS TRIGGER AS $$
        BEGIN
            IF NEW.start_date IS NULL THEN
                NEW.start_date := MAKE_DATE(NEW.year, 1, 1);
            END IF;
            IF NEW.end_date IS NULL THEN
                NEW.end_date := MAKE_DATE(NEW.year, 12, 31);
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    connection.execute(
        """
        DROP TRIGGER IF EXISTS trg_annual_growth_plan_default_dates
        ON annual_growth_plan
        """
    )
    connection.execute(
        """
        CREATE TRIGGER trg_annual_growth_plan_default_dates
        BEFORE INSERT ON annual_growth_plan
        FOR EACH ROW
        EXECUTE FUNCTION set_annual_growth_plan_default_dates()
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS growth_goal (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            gap_id BIGINT NOT NULL REFERENCES gap(id) ON DELETE CASCADE,
            annual_growth_plan_id BIGINT NOT NULL
                REFERENCES annual_growth_plan(id) ON DELETE CASCADE,
            l3_code TEXT NOT NULL,
            year INT NOT NULL,
            target_level INT NOT NULL,
            priority TEXT NOT NULL DEFAULT '中'
                CHECK (priority IN ('高', '中', '低')),
            UNIQUE(annual_growth_plan_id, l3_code)
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS plan_item (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            annual_growth_plan_id BIGINT NOT NULL
                REFERENCES annual_growth_plan(id) ON DELETE CASCADE,
            growth_goal_id BIGINT REFERENCES growth_goal(id) ON DELETE CASCADE,
            l3_code TEXT NOT NULL,
            current_level INT NOT NULL,
            target_level INT NOT NULL,
            priority TEXT NOT NULL
                CHECK (priority IN ('高', '中', '低')),
            learning_material TEXT,
            learning_task_content TEXT,
            expected_output TEXT,
            estimated_hours TEXT,
            plan_start_date DATE,
            plan_end_date DATE,
            target_month INT,
            status TEXT NOT NULL DEFAULT '未开始'
                CHECK (status IN (
                    '未开始', '进行中', '已完成', '延期', '暂停', '取消'
                )),
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            source_assessment_id BIGINT REFERENCES assessment(id) ON DELETE RESTRICT,
            source_assessment_detail_id BIGINT
                REFERENCES assessment_detail(id) ON DELETE RESTRICT,
            planning_snapshot_id BIGINT
                REFERENCES capability_standard_planning_snapshot(id) ON DELETE RESTRICT,
            l3_node_id BIGINT,
            l1_code TEXT,
            l1_name TEXT,
            l2_code TEXT,
            l2_name TEXT,
            l3_name TEXT,
            scope_type TEXT CHECK (
                scope_type IS NULL
                OR scope_type IN ('current_required', 'target_progressive')
            ),
            standard_target_level INT CHECK (
                standard_target_level IS NULL OR standard_target_level BETWEEN 1 AND 5
            ),
            adjusted_target_level INT CHECK (
                adjusted_target_level IS NULL OR adjusted_target_level BETWEEN 1 AND 5
            ),
            effective_target_level INT CHECK (
                effective_target_level IS NULL OR effective_target_level BETWEEN 1 AND 5
            ),
            standard_job_level_snapshot TEXT CHECK (
                standard_job_level_snapshot IS NULL
                OR standard_job_level_snapshot IN ('P4', 'P5', 'P6', 'P7', 'P8')
            ),
            member_current_level_snapshot TEXT CHECK (
                member_current_level_snapshot IS NULL
                OR member_current_level_snapshot IN ('P4', 'P5', 'P6', 'P7', 'P8')
            ),
            member_target_level_snapshot TEXT CHECK (
                member_target_level_snapshot IS NULL
                OR member_target_level_snapshot IN ('P4', 'P5', 'P6', 'P7', 'P8')
            ),
            plan_quarter TEXT CHECK (
                plan_quarter IS NULL OR plan_quarter IN ('Q1', 'Q2', 'Q3', 'Q4')
            ),
            plan_month INT CHECK (plan_month IS NULL OR plan_month BETWEEN 1 AND 12),
            planning_source_type TEXT CHECK (
                planning_source_type IS NULL
                OR planning_source_type IN ('assessment_approval')
            ),
            assessment_revision BIGINT,
            gap_value INT CHECK (gap_value IS NULL OR gap_value >= 0),
            include_in_plan BOOLEAN,
            CHECK (
                plan_quarter IS NULL OR plan_month IS NULL
                OR (plan_quarter = 'Q1' AND plan_month BETWEEN 1 AND 3)
                OR (plan_quarter = 'Q2' AND plan_month BETWEEN 4 AND 6)
                OR (plan_quarter = 'Q3' AND plan_month BETWEEN 7 AND 9)
                OR (plan_quarter = 'Q4' AND plan_month BETWEEN 10 AND 12)
            ),
            CHECK (
                planning_source_type IS DISTINCT FROM 'assessment_approval'
                OR (include_in_plan = TRUE AND priority IN ('高', '中', '低'))
            ),
            UNIQUE(annual_growth_plan_id, l3_code),
            UNIQUE(growth_goal_id)
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS learning_task (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            plan_item_id BIGINT NOT NULL REFERENCES plan_item(id) ON DELETE CASCADE,
            l3_code TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT '未开始'
                CHECK (status IN (
                    '未开始', '进行中', '待 Evidence Review',
                    '已完成', '延期', '暂停', '取消'
                )),
            actual_start_date DATE,
            actual_end_date DATE,
            actual_hours INT DEFAULT 0,
            completion_quality TEXT,
            review_conclusion TEXT,
            next_action TEXT,
            UNIQUE(plan_item_id)
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS learning_progress_log (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            task_id BIGINT NOT NULL REFERENCES learning_task(id) ON DELETE CASCADE,
            record_date DATE NOT NULL,
            actual_hours INT NOT NULL CHECK (actual_hours >= 0),
            note TEXT,
            recorder_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_learning_progress_log_task_id
        ON learning_progress_log(task_id)
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_learning_progress_log_recorder_id
        ON learning_progress_log(recorder_id)
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS evidence (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            learning_task_id BIGINT NOT NULL
                REFERENCES learning_task(id) ON DELETE CASCADE,
            l3_code TEXT NOT NULL,
            version_number INT NOT NULL CHECK (version_number > 0),
            content TEXT,
            evidence_link TEXT,
            status TEXT NOT NULL DEFAULT '草稿'
                CHECK (status IN (
                    '草稿', '待 Review', '通过', '需补充', '驳回', '已归档'
                )),
            submitted_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE(learning_task_id, version_number)
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_evidence_learning_task_id
        ON evidence(learning_task_id)
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS evidence_review (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            evidence_id BIGINT NOT NULL UNIQUE
                REFERENCES evidence(id) ON DELETE CASCADE,
            buddy_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE,
            status TEXT NOT NULL DEFAULT '待 Review'
                CHECK (status IN ('待 Review', '通过', '需补充', '驳回', '已闭环')),
            conclusion TEXT CHECK (conclusion IN ('通过', '需补充', '驳回')),
            feedback TEXT,
            reviewed_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_evidence_review_evidence_id
        ON evidence_review(evidence_id)
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_evidence_review_buddy_id
        ON evidence_review(buddy_id)
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS capability_profile (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            member_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE,
            year INT NOT NULL,
            status TEXT NOT NULL DEFAULT '已生成'
                CHECK (status IN ('生成中', '已生成')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE(member_id, year)
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS team_annual_capability_plan (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code TEXT NOT NULL UNIQUE,
            year INT NOT NULL UNIQUE,
            publisher_id BIGINT NOT NULL,
            resource_arrangement TEXT,
            description TEXT,
            published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            status TEXT NOT NULL DEFAULT '已发布'
                CHECK (status IN ('已发布', '已归档')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS team_annual_capability_plan_domain (
            plan_id BIGINT NOT NULL
                REFERENCES team_annual_capability_plan(id) ON DELETE CASCADE,
            l1_code TEXT NOT NULL,
            PRIMARY KEY (plan_id, l1_code)
        )
        """
    )
    # uniq_plan_first_source_assessment / uniq_plan_item_source_detail are
    # owned by migration v0009: the bootstrap runs BEFORE migrations on old
    # ledgers, and the source columns only exist on tables v0009 has extended
    # (a real v0003/v0008 database crashes here with UndefinedColumn before
    # the migration runner ever runs).  v0009 creates both with IF NOT EXISTS,
    # so fresh installs get them from the migration too — never from here.
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS annual_plan_change_proposal (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            member_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE RESTRICT,
            year INT NOT NULL,
            source_assessment_id BIGINT NOT NULL
                REFERENCES assessment(id) ON DELETE RESTRICT,
            target_annual_growth_plan_id BIGINT NOT NULL
                REFERENCES annual_growth_plan(id) ON DELETE RESTRICT,
            status TEXT NOT NULL DEFAULT '待处理'
                CHECK (status IN ('待处理')),
            created_by BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE RESTRICT,
            summary JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE (source_assessment_id)
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS annual_plan_change_proposal_detail (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            proposal_id BIGINT NOT NULL
                REFERENCES annual_plan_change_proposal(id) ON DELETE CASCADE,
            source_assessment_detail_id BIGINT NOT NULL
                REFERENCES assessment_detail(id) ON DELETE RESTRICT,
            assessment_id BIGINT NOT NULL,
            l3_node_id BIGINT NOT NULL,
            l1_code TEXT NOT NULL,
            l1_name TEXT NOT NULL,
            l2_code TEXT NOT NULL,
            l2_name TEXT NOT NULL,
            l3_code TEXT NOT NULL,
            l3_name TEXT NOT NULL,
            scope_type TEXT CHECK (
                scope_type IS NULL
                OR scope_type IN ('current_required', 'target_progressive')
            ),
            current_level INT CHECK (
                current_level IS NULL OR current_level BETWEEN 0 AND 5
            ),
            standard_target_level INT CHECK (
                standard_target_level IS NULL OR standard_target_level BETWEEN 1 AND 5
            ),
            adjusted_target_level INT CHECK (
                adjusted_target_level IS NULL OR adjusted_target_level BETWEEN 1 AND 5
            ),
            effective_target_level INT CHECK (
                effective_target_level IS NULL OR effective_target_level BETWEEN 1 AND 5
            ),
            gap_value INT CHECK (gap_value IS NULL OR gap_value >= 0),
            member_priority TEXT CHECK (
                member_priority IS NULL OR member_priority IN ('高', '中', '低', '暂缓')
            ),
            include_in_plan BOOLEAN,
            plan_quarter TEXT CHECK (
                plan_quarter IS NULL OR plan_quarter IN ('Q1', 'Q2', 'Q3', 'Q4')
            ),
            plan_month INT CHECK (plan_month IS NULL OR plan_month BETWEEN 1 AND 12),
            standard_job_level_snapshot TEXT CHECK (
                standard_job_level_snapshot IS NULL
                OR standard_job_level_snapshot IN ('P4', 'P5', 'P6', 'P7', 'P8')
            ),
            member_current_level_snapshot TEXT CHECK (
                member_current_level_snapshot IS NULL
                OR member_current_level_snapshot IN ('P4', 'P5', 'P6', 'P7', 'P8')
            ),
            member_target_level_snapshot TEXT CHECK (
                member_target_level_snapshot IS NULL
                OR member_target_level_snapshot IN ('P4', 'P5', 'P6', 'P7', 'P8')
            ),
            capability_standard_version_id BIGINT NOT NULL,
            planning_snapshot_id BIGINT,
            assessment_revision BIGINT NOT NULL,
            planning_source_type TEXT NOT NULL DEFAULT 'assessment_approval'
                CHECK (planning_source_type IN ('assessment_approval')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE (source_assessment_detail_id),
            CHECK (
                plan_quarter IS NULL OR plan_month IS NULL
                OR (plan_quarter = 'Q1' AND plan_month BETWEEN 1 AND 3)
                OR (plan_quarter = 'Q2' AND plan_month BETWEEN 4 AND 6)
                OR (plan_quarter = 'Q3' AND plan_month BETWEEN 7 AND 9)
                OR (plan_quarter = 'Q4' AND plan_month BETWEEN 10 AND 12)
            )
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS review_idempotency_key (
            buddy_id BIGINT NOT NULL REFERENCES tcp_user(id) ON DELETE CASCADE,
            idempotency_key TEXT NOT NULL,
            assessment_id BIGINT NOT NULL
                REFERENCES assessment(id) ON DELETE CASCADE,
            review_id BIGINT NOT NULL
                REFERENCES assessment_review(id) ON DELETE CASCADE,
            fingerprint TEXT NOT NULL,
            response JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            PRIMARY KEY (buddy_id, idempotency_key)
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_review_idem_assessment
        ON review_idempotency_key(assessment_id)
        """
    )
